//! Canonical diagnostic code enum for TalkBank parsing/validation.
//!
//! GENERATED by `spec_gen` from `spec/codes/error-codes.toml`.
//! DO NOT EDIT BY HAND: change the registry.
//!
//! Regenerate with `just spec-gen`; `just spec-check` reports whether this
//! copy is current without writing anything.
//!
//! Each variant's rustdoc is the registry's `summary`, and `#[status(planned)]`
//! is emitted from its `status`, so the enum cannot disagree with the specs
//! about which checks run. The gate that used to reconcile the two is gone.
//!
//! # Related CHAT Manual Sections
//!
//! - <https://talkbank.org/0info/manuals/CHAT.html#File_Format>

// RETIRED numbers, never reused. Enforced by the registry, which refuses
// to register one; listed here for a reader who reaches the enum first.
// W210: Missing whitespace before content (a glued terminator `hello.`). Retired 2026-07-16 by maintainer ruling: no production code ever emitted it, and real CLAN CHECK accepts the construct.
// W211: Missing whitespace after an overlap marker. Retired 2026-07-16 by maintainer ruling: never emitted, and overlap markers hug their content by design, so the shape is valid CA notation.
// W601: Empty user-defined tier. RENUMBERED to E756 on 2026-07-16: it always fired as a hard error, so the warning prefix was the bug.
// W602: Deprecated %xLABEL. Deleted 2026-07-16: the Phon %x-tier fold routes every known label to a typed tier parser, so the check was dead code.
// W999: Generic legacy warning. Retired 2026-07-31: its only reference anywhere was the generated DiagnosticKind arm itself; no emit site ever constructed it.
// E254: UndeclaredExplicitWordLanguage. Retired 2026-07-15: an explicit word-level `@s:CODE` deliberately carries no requirement to be declared in `@Languages` (docs/design/2026-07-15-at-s-language-declaration-decision.md part 1).
// E366: Long feature begin/end label mismatch. Retired 2026-07-31 in the spec/ErrorCode divergence closure: its only reference anywhere was the generated DiagnosticKind arm itself; no emit site ever constructed it.
// E369: Nonvocal begin/end label mismatch. Retired 2026-07-31, same closure and same reason as E366: no emit site ever constructed it.
// E700: Unexpected node in tier content. Retired 2026-07-31 in the spec/ErrorCode divergence closure: no emit site ever constructed it.
// E703: Unexpected node in morphology tier. Retired 2026-07-31, same closure and same reason as E700. Distinct from temporal.rs's separate note that E702/E703 are reserved for a strict timeline mode: that never-built feature would need its own new variant, not this number.
// E754: LetterFormMultipleLetters. Retired 2026-08-11: it required an `@l` letter form to carry exactly one letter of stem but counted CHARACTERS, and a digraph is one letter written with two (Welsh `ll`, Dutch `ij`, Hungarian `sz`), so it reported a spurious error on valid CHAT and could not do better, never seeing the word's language. CLAN reached the same conclusion four days earlier, retiring its error 76.
// E214: Empty scoped annotation content. Retired 2026-08-26, and it had drifted into TWO rules under one number, neither of which could fire. It began as "bare [*] carries no error code" and was deliberately DISABLED as leniency Decision 1, because reference files use bare [*] as valid CHAT; its spec file still documented that rule. The code was then reused for "the scoped-annotation LIST is empty", which no input reaches: an empty bracket is E316, and the only empty list in the model was the parser wrapping every bare 0, never validated because Action does not implement Validate. AnnotatedContentAnnotations is non-empty by construction now, so the second rule is unrepresentable and the first stays retired. The registry already recorded status = not_implemented.

/// Standard error codes for CHAT parsing and validation.
///
/// The `#[error_code_enum]` attribute macro derives, from the `#[code("...")]`
/// attributes below: the serde renames, `as_str`, `parse_exact`,
/// `Display`, `documentation_url`, `iter` and `planned`. The attributes
/// themselves come from `spec/codes/error-codes.toml`, so the code strings, the
/// variant names and the enforcement split all have one owner and no gate
/// standing between two copies of them.
///
/// See [`super::CheckStatus`] for the enforced/planned distinction and
/// [`ErrorCode::check_status`] for reading it off a value.
#[talkbank_derive::error_code_enum]
pub enum ErrorCode {
    /// Internal error (unexpected condition in parser or validator).
    #[code("E001")]
    InternalError,
    /// Test-only error code used in unit tests.
    #[code("E002")]
    TestError,
    /// Input string is empty.
    #[code("E003")]
    #[status(planned)]
    EmptyString,
    /// Invalid line format in the CHAT file.
    #[code("E101")]
    #[status(planned)]
    InvalidLineFormat,
    /// Missing form type on special word.
    #[code("E202")]
    MissingFormType,
    /// Invalid form type value.
    #[code("E203")]
    InvalidFormType,
    /// Unknown annotation type in word.
    #[code("E207")]
    UnknownAnnotation,
    /// Replacement annotation is empty.
    #[code("E208")]
    EmptyReplacement,
    /// Spoken content portion of word is empty.
    #[code("E209")]
    EmptySpokenContent,
    /// Illegal replacement for fragment (deprecated: use E387).
    #[code("E210")]
    IllegalReplacementForFragment,
    /// Invalid word format.
    #[code("E212")]
    #[status(planned)]
    InvalidWordFormat,
    /// Untranscribed marker in replacement (deprecated: use E391).
    #[code("E213")]
    UntranscribedInReplacement,
    /// Illegal digits in word content.
    #[code("E220")]
    IllegalDigits,
    /// Unbalanced CA (Conversation Analysis) delimiter.
    #[code("E230")]
    UnbalancedCADelimiter,
    /// Unbalanced shortening markers.
    #[code("E231")]
    UnbalancedShortening,
    /// Invalid compound marker position.
    #[code("E232")]
    InvalidCompoundMarkerPosition,
    /// Empty part in compound word.
    #[code("E233")]
    EmptyCompoundPart,
    /// Illegal use of untranscribed marker.
    #[code("E241")]
    IllegalUntranscribed,
    /// Unbalanced quotation marks within a word.
    #[code("E242")]
    UnbalancedQuotation,
    /// Illegal characters in word content.
    #[code("E243")]
    IllegalCharactersInWord,
    /// Consecutive stress markers in word.
    #[code("E244")]
    ConsecutiveStressMarkers,
    /// Stress marker not placed before spoken material.
    #[code("E245")]
    StressNotBeforeSpokenMaterial,
    /// Lengthening marker not placed after spoken material.
    #[code("E246")]
    #[status(planned)]
    LengtheningNotAfterSpokenMaterial,
    /// Multiple primary stress markers in one word.
    #[code("E247")]
    MultiplePrimaryStress,
    /// Tertiary language needs an explicit language code.
    #[code("E248")]
    TertiaryLanguageNeedsExplicitCode,
    /// Missing language context for language-tagged word.
    #[code("E249")]
    MissingLanguageContext,
    /// Secondary stress marker without primary stress.
    #[code("E250")]
    SecondaryStressWithoutPrimary,
    /// Word content text is empty.
    #[code("E251")]
    #[status(planned)]
    EmptyWordContentText,
    /// Syllable pause not between spoken material.
    #[code("E252")]
    SyllablePauseNotBetweenSpokenMaterial,
    /// Word content is empty.
    #[code("E253")]
    EmptyWordContent,
    /// Whole-utterance language switch should use `[- LANG]` instead of tagging every word with `@s`.
    #[code("E255")]
    WholeUtteranceLanguageSwitchShouldUsePrecode,
    /// Curly single quotation mark (U+2018 or U+2019) used as a word
    /// character; CHAT requires the ASCII apostrophe. CLAN CHECK 138/139.
    #[code("E256")]
    IllegalCurlyQuote,
    /// Consecutive commas (`,,`), should use single comma or `‚` (CLAN CHECK 107)
    #[code("E258")]
    ConsecutiveCommas,
    /// Comma after non-spoken content (paralinguistic event, filler, nonword, placeholder, omitted word)
    #[code("E259")]
    CommaAfterNonSpokenContent,
    /// Missing main tier (speaker line) in utterance.
    #[code("E301")]
    MissingMainTier,
    /// Expected tree-sitter node is missing.
    #[code("E302")]
    #[status(planned)]
    MissingNode,
    /// General syntax error in CHAT input.
    #[code("E303")]
    #[status(planned)]
    SyntaxError,
    /// Missing speaker code on main tier line.
    #[code("E304")]
    #[status(planned)]
    MissingSpeaker,
    /// Missing utterance terminator (`.`, `?`, `!`, etc.).
    #[code("E305")]
    MissingTerminator,
    /// Utterance contains no words or content.
    #[code("E306")]
    EmptyUtterance,
    /// Speaker code is syntactically invalid.
    #[code("E307")]
    InvalidSpeaker,
    /// Speaker code is not declared in `@Participants`.
    #[code("E308")]
    UndeclaredSpeaker,
    /// Unexpected syntax encountered during parsing.
    #[code("E309")]
    #[status(planned)]
    UnexpectedSyntax,
    /// Parser failed to produce a valid parse tree.
    #[code("E310")]
    #[status(planned)]
    ParseFailed,
    /// Unexpected node type in the parse tree.
    ///
    /// No longer planned as of 2026-08-11: an unclosed replacement bracket
    /// (`*CHI:\t[: unclosed [* error] .`) reaches it and reports "Unclosed
    /// replacement bracket". Its spec had stayed `not_implemented` on the
    /// strength of a note saying tree-sitter recovery made it unreachable
    /// because E316 fired first, which the parser had since outgrown.
    #[code("E311")]
    UnexpectedNode,
    /// Unclosed bracket in annotation or word content.
    #[code("E312")]
    #[status(planned)]
    UnclosedBracket,
    /// Unclosed parenthesis in annotation or word content.
    #[code("E313")]
    UnclosedParenthesis,
    /// Annotation is syntactically incomplete.
    #[code("E314")]
    IncompleteAnnotation,
    /// Invalid control character in input.
    #[code("E315")]
    InvalidControlCharacter,
    /// Content could not be parsed.
    #[code("E316")]
    UnparsableContent,
    /// Line could not be parsed.
    #[code("E319")]
    #[status(planned)]
    UnparsableLine,
    /// Header line could not be parsed.
    #[code("E320")]
    #[status(planned)]
    UnparsableHeader,
    /// Utterance could not be parsed.
    #[code("E321")]
    #[status(planned)]
    UnparsableUtterance,
    /// Empty colon with no content following it.
    #[code("E322")]
    #[status(planned)]
    EmptyColon,
    /// Missing colon after speaker code.
    #[code("E323")]
    #[status(planned)]
    MissingColonAfterSpeaker,
    /// Unrecognized error in utterance content.
    #[code("E324")]
    UnrecognizedUtteranceError,
    /// Unexpected child node in utterance.
    #[code("E325")]
    #[status(planned)]
    UnexpectedUtteranceChild,
    /// Unexpected line type in CHAT file.
    #[code("E326")]
    UnexpectedLineType,
    /// Error during tree-sitter CST traversal.
    #[code("E330")]
    TreeParsingError,
    /// Unexpected node encountered in a specific parsing context.
    #[code("E331")]
    #[status(planned)]
    UnexpectedNodeInContext,
    /// Unknown base content type in word.
    #[code("E340")]
    UnknownBaseContent,
    /// Unbalanced quotation marks spanning across utterances.
    #[code("E341")]
    #[status(planned)]
    UnbalancedQuotationCrossUtterance,
    /// Tree-sitter inserted a MISSING placeholder for a required element.
    #[code("E342")]
    MissingRequiredElement,
    /// Invalid nesting of scoped annotations.
    #[code("E344")]
    #[status(planned)]
    InvalidContentAnnotationNesting,
    /// Unmatched scoped annotation end marker.
    #[code("E346")]
    #[status(planned)]
    UnmatchedContentAnnotationEnd,
    /// Unbalanced overlap markers.
    #[code("E347")]
    UnbalancedOverlap,
    /// Missing overlap end marker.
    #[code("E348")]
    #[status(planned)]
    MissingOverlapEnd,
    /// Missing opening quotation mark.
    #[code("E351")]
    #[status(planned)]
    MissingQuoteBegin,
    /// Missing closing quotation mark.
    #[code("E352")]
    #[status(planned)]
    MissingQuoteEnd,
    /// Missing context for other-completion annotation.
    #[code("E353")]
    #[status(planned)]
    MissingOtherCompletionContext,
    /// Missing trailing-off terminator.
    #[code("E354")]
    #[status(planned)]
    MissingTrailingOffTerminator,
    /// Interleaved scoped annotations (overlapping scopes).
    #[code("E355")]
    #[status(planned)]
    InterleavedContentAnnotations,
    /// Unmatched underline begin marker.
    #[code("E356")]
    UnmatchedUnderlineBegin,
    /// Unmatched underline end marker.
    #[code("E357")]
    UnmatchedUnderlineEnd,
    /// Unmatched long feature begin marker.
    #[code("E358")]
    UnmatchedLongFeatureBegin,
    /// Unmatched long feature end marker.
    #[code("E359")]
    UnmatchedLongFeatureEnd,
    /// Invalid media bullet format.
    #[code("E360")]
    #[status(planned)]
    InvalidMediaBullet,
    /// Invalid timestamp value in media bullet.
    #[code("E361")]
    #[status(planned)]
    InvalidTimestamp,
    /// Timestamp end is before start (backwards range).
    #[code("E362")]
    TimestampBackwards,
    /// Invalid postcode format.
    #[code("E363")]
    InvalidPostcode,
    /// Malformed word content.
    #[code("E364")]
    #[status(planned)]
    MalformedWordContent,
    /// Malformed tier content.
    #[code("E365")]
    #[status(planned)]
    MalformedTierContent,
    /// Unmatched nonvocal begin marker.
    #[code("E367")]
    UnmatchedNonvocalBegin,
    /// Unmatched nonvocal end marker.
    #[code("E368")]
    UnmatchedNonvocalEnd,
    /// Structural ordering error in utterance elements.
    #[code("E370")]
    StructuralOrderError,
    /// Pause marker inside a phonological group.
    #[code("E371")]
    PauseInPhoGroup,
    /// Nested quotation (quotation inside quotation).
    #[code("E372")]
    NestedQuotation,
    /// Invalid overlap index value.
    #[code("E373")]
    InvalidOverlapIndex,
    /// Failed to parse scoped annotation content.
    #[code("E375")]
    ContentAnnotationParseError,
    /// Failed to parse replacement annotation content.
    #[code("E376")]
    ReplacementParseError,
    /// A retracing marker whose only content is another retracing marker.
    ///
    /// A marker retraces the material immediately to its left, and a marker is
    /// not material. Ruled an error by the CHAT maintainer, 2026-08-07.
    ///
    /// Named for the SHAPE, not a spelling. The lowering folds a marker run
    /// into a left-associative chain, so the unbracketed `на [//] [/] на` and
    /// the bracketed `<<a> [/]> [//]` produce the same tree and one rule
    /// catches both; an `AdjacentRetraceMarkers` name described only the first
    /// and read as a different, narrower rule than the one that ships.
    #[code("E377")]
    RetraceWithNoMaterial,
    /// A retracing marker applied to material containing no words at all.
    ///
    /// A marker retraces the WORDS to its left, and a laugh is not a word.
    /// Ruled by the CHAT maintainer, 2026-08-07: "No, not legal. You can't
    /// retrace a laugh."
    ///
    /// Disjoint from `RetraceWithNoMaterial` despite the neighbouring names.
    /// That one is a marker over a lone marker, whose inner retrace still holds
    /// words; this one is material with no word anywhere beneath it. The
    /// repairs differ too: drop a marker there, retrace the words here.
    #[code("E378")]
    RetraceWithoutWords,
    /// Failed to parse `%mor` tier content.
    #[code("E382")]
    #[status(planned)]
    MorParseError,
    /// Replacement `[: text]` on fragment or phonological fragment (`&+`).
    #[code("E387")]
    ReplacementOnFragment,
    /// Replacement `[: text]` on nonword (`&~`).
    #[code("E388")]
    ReplacementOnNonword,
    /// Replacement `[: text]` on filler (`&-`).
    #[code("E389")]
    ReplacementOnFiller,
    /// Replacement text contains an omission (`0word`).
    #[code("E390")]
    ReplacementContainsOmission,
    /// Replacement text contains untranscribed marker (`xxx`/`yyy`/`www`).
    #[code("E391")]
    ReplacementContainsUntranscribed,
    /// Duplicate dependent tier on same utterance.
    #[code("E401")]
    DuplicateDependentTier,
    /// Dependent tier without a preceding main tier.
    #[code("E404")]
    OrphanedDependentTier,
    /// Duplicate header line.
    #[code("E501")]
    DuplicateHeader,
    /// Missing `@End` header.
    #[code("E502")]
    MissingEndHeader,
    /// Missing `@UTF8` header.
    #[code("E503")]
    MissingUTF8Header,
    /// Missing required header (e.g., `@Participants`).
    #[code("E504")]
    MissingRequiredHeader,
    /// Invalid `@ID` header format.
    #[code("E505")]
    InvalidIDFormat,
    /// Empty `@Participants` header.
    #[code("E506")]
    EmptyParticipantsHeader,
    /// Empty `@Languages` header.
    #[code("E507")]
    EmptyLanguagesHeader,
    /// Empty `@Date` header.
    #[code("E508")]
    EmptyDateHeader,
    /// Empty `@Media` header.
    #[code("E509")]
    EmptyMediaHeader,
    /// Empty language field in `@ID` header.
    #[code("E510")]
    EmptyIDLanguage,
    /// Empty speaker field in `@ID` header.
    #[code("E511")]
    EmptyIDSpeaker,
    /// Empty participant code in `@Participants`.
    #[code("E512")]
    EmptyParticipantCode,
    /// Empty participant role in `@Participants`.
    #[code("E513")]
    EmptyParticipantRole,
    /// Empty corpus field (2nd field) in `@ID` header. The corpus name is
    /// required: `@ID:` is `lang|corpus|code|...`, and a blank corpus is
    /// invalid. Corresponds to CLAN CHECK error 63 ("Missing Corpus name").
    #[code("E514")]
    EmptyIDCorpus,
    /// Empty role field in `@ID` header.
    #[code("E515")]
    EmptyIDRole,
    /// Empty date value.
    #[code("E516")]
    EmptyDate,
    /// Invalid age format in `@ID` header.
    #[code("E517")]
    InvalidAgeFormat,
    /// Invalid date format.
    #[code("E518")]
    InvalidDateFormat,
    /// Invalid ISO 639 language code.
    #[code("E519")]
    InvalidLanguageCode,
    /// Speaker code not defined in `@Participants`.
    #[code("E522")]
    SpeakerNotDefined,
    /// `@ID` header references an undeclared participant.
    #[code("E523")]
    OrphanIDHeader,
    /// `@Birth` header references an unknown participant.
    #[code("E524")]
    BirthUnknownParticipant,
    /// Unknown or unrecognized header type.
    #[code("E525")]
    UnknownHeader,
    /// Unmatched `@Bg` (begin gem) without corresponding `@Eg`.
    #[code("E526")]
    UnmatchedBeginGem,
    /// Unmatched `@Eg` (end gem) without corresponding `@Bg`.
    #[code("E527")]
    UnmatchedEndGem,
    /// Gem begin/end labels do not match.
    #[code("E528")]
    GemLabelMismatch,
    /// Nested `@Bg` (begin gem inside existing gem scope).
    #[code("E529")]
    NestedBeginGem,
    /// Lazy gem (`@G`) used inside an explicit gem scope.
    #[code("E530")]
    LazyGemInsideScope,
    /// `@Media` filename does not match the file being parsed.
    #[code("E531")]
    MediaFilenameMismatch,
    /// Invalid participant role value.
    #[code("E532")]
    InvalidParticipantRole,
    /// Empty `@Options` header.
    #[code("E533")]
    EmptyOptionsHeader,
    /// Unsupported `@Options` value.
    #[code("E534")]
    UnsupportedOption,
    /// Unsupported `@Media` type (not `audio`, `video`, or `missing`).
    #[code("E535")]
    UnsupportedMediaType,
    /// Unsupported `@Media` status value.
    #[code("E536")]
    UnsupportedMediaStatus,
    /// Unsupported `@Number` value.
    #[code("E537")]
    UnsupportedNumber,
    /// Unsupported `@Recording Quality` value.
    #[code("E538")]
    UnsupportedRecordingQuality,
    /// Unsupported `@Transcription` value.
    #[code("E539")]
    UnsupportedTranscription,
    /// Invalid `@Time Duration` format.
    #[code("E540")]
    InvalidTimeDuration,
    /// Invalid `@Time Start` format.
    #[code("E541")]
    InvalidTimeStart,
    /// Unsupported `@ID` sex value (not `male` or `female`).
    #[code("E542")]
    UnsupportedSex,
    /// Header out of canonical order (e.g., `@Options` before `@Participants`).
    #[code("E543")]
    HeaderOutOfOrder,
    /// `@Media` header declares linkage (no `unlinked` / `missing` /
    /// `notrans` status) but the transcript carries no timing evidence
    /// (no bullets on any utterance, no `%wor` bullets, no `@Bg`/`@Eg`
    /// time range). Reinstates the legacy CHAT validation check.
    #[code("E544")]
    MediaLinkageWithoutTiming,
    /// Invalid `@Birth of` date format, must match `DD-MMM-YYYY`
    /// per CLAN `depfile.cut`'s `@d<dd-lll-yyyy>` template.
    #[code("E545")]
    InvalidBirthDateFormat,
    /// Unsupported `@ID` SES value.
    #[code("E546")]
    UnsupportedSesValue,
    /// A constant participant-specific header (`@Birth of`, `@Birthplace of`,
    /// or `@L1 of`) does not immediately follow the `@ID` block: a changeable
    /// header (e.g. `@Comment`, `@Date`) appears between the `@ID` headers and
    /// the constant header. Per the CHAT manual these constant headers must
    /// directly follow `@ID`. Corresponds to CLAN CHECK error 127.
    #[code("E547")]
    ConstantHeaderOutOfOrder,
    /// An `@ID` header does not immediately follow the `@Participants` /
    /// `@Options` headers (or another `@ID`): a changeable header such as
    /// `@Comment` appears between `@Participants`/`@Options` and the `@ID`
    /// block. Per the CHAT manual the `@ID` block directly follows
    /// `@Participants` (and the optional `@Options`). Corresponds to CLAN
    /// CHECK error 126.
    #[code("E548")]
    IdHeaderOutOfOrder,
    /// The same speaker code is declared more than once in the `@Participants`
    /// header. Each participant must be declared exactly once. Corresponds to
    /// CLAN CHECK error 13.
    #[code("E549")]
    DuplicateSpeakerDeclaration,
    /// The `@Participants` header ends with a trailing comma (a stray comma
    /// after the last participant, with no participant following it). The
    /// participant list is comma-separated, so a trailing comma is a dangling
    /// separator rather than an empty header. Corresponds to CLAN CHECK error
    /// 100 ("Commas at the end of PARTICIPANTS tier are not allowed").
    #[code("E550")]
    TrailingCommaInParticipants,
    /// The `@Options` header does not immediately follow the `@Participants`
    /// header. Per the CHAT spec the optional `@Options` line, when present,
    /// must sit directly after `@Participants`, before the `@ID` block or any
    /// other header. An `@Options` whose immediately-preceding header is
    /// something else (e.g. an `@ID` or `@Comment`), once `@Participants` has
    /// been seen, is an ordering violation. Corresponds to CLAN CHECK error 125
    /// ("\"@Options\" header must immediately follow \"@Participants:\" header").
    #[code("E551")]
    OptionsHeaderOutOfOrder,
    /// The `@Media` header declares `unlinked` status, yet the transcript
    /// contains timing bullets. `unlinked` means the media file exists but its
    /// utterances have not been aligned to timestamps; the presence of timing
    /// bullets contradicts that, so the `unlinked` qualifier must be removed
    /// (the media is in fact linked). This is the inverse of
    /// [`MediaLinkageWithoutTiming`](Self::MediaLinkageWithoutTiming) (E544) and
    /// corresponds to CLAN CHECK error 124 ("remove \"unlinked\" from @Media
    /// header").
    #[code("E552")]
    MediaUnlinkedWithTiming,
    /// Generic tier validation error.
    #[code("E600")]
    TierValidationError,
    /// Invalid dependent tier name or format.
    #[code("E601")]
    InvalidDependentTier,
    /// Malformed tier header line.
    #[code("E602")]
    MalformedTierHeader,
    /// Invalid `%tim` tier format.
    #[code("E603")]
    InvalidTimTierFormat,
    /// `%gra` tier present without corresponding `%mor` tier.
    #[code("E604")]
    GraWithoutMor,
    /// Unsupported dependent tier (not a standard `%` tier or `%x` user-defined tier).
    #[code("E605")]
    UnsupportedDependentTier,
    /// Tier begin time is not monotonically increasing (CLAN Error 83).
    #[code("E701")]
    TierBeginTimeNotMonotonic,
    /// Invalid morphology format on `%mor` tier.
    #[code("E702")]
    #[status(planned)]
    InvalidMorphologyFormat,
    /// Speaker overlaps with themselves (CLAN Error 133).
    #[code("E704")]
    SpeakerSelfOverlap,
    /// `%mor` tier has fewer words than main tier.
    #[code("E705")]
    MorCountMismatchTooFew,
    /// `%mor` tier has more words than main tier.
    #[code("E706")]
    MorCountMismatchTooMany,
    /// `%mor` tier terminator presence does not match main tier.
    #[code("E707")]
    #[status(planned)]
    MorTerminatorPresenceMismatch,
    /// Malformed grammar relation on `%gra` tier.
    #[code("E708")]
    #[status(planned)]
    MalformedGrammarRelation,
    /// Invalid index in grammar relation.
    #[code("E709")]
    InvalidGrammarIndex,
    /// Unexpected node in `%gra` tier.
    #[code("E710")]
    UnexpectedGrammarNode,
    /// `%mor` word has empty stem, POS category, prefix, or suffix.
    #[code("E711")]
    #[status(planned)]
    MorEmptyContent,
    /// `%gra` word index is out of range.
    #[code("E712")]
    GraInvalidWordIndex,
    /// `%gra` head index is out of range.
    #[code("E713")]
    GraInvalidHeadIndex,
    /// `%pho`, `%mod`, or `%wor` tier has fewer alignable words than main tier.
    #[code("E714")]
    PhoCountMismatchTooFew,
    /// `%pho`, `%mod`, or `%wor` tier has more alignable words than main tier.
    #[code("E715")]
    PhoCountMismatchTooMany,
    /// `%mor` tier terminator value does not match main tier.
    #[code("E716")]
    MorTerminatorValueMismatch,
    /// `%sin` tier has fewer words than main tier.
    #[code("E718")]
    SinCountMismatchTooFew,
    /// `%sin` tier has more words than main tier.
    #[code("E719")]
    SinCountMismatchTooMany,
    /// `%mor` and `%gra` tier word counts do not match.
    #[code("E720")]
    MorGraCountMismatch,
    /// `%gra` indices are not sequential.
    #[code("E721")]
    GraNonSequentialIndex,
    /// `%gra` tier has no ROOT relation.
    #[code("E722")]
    GraNoRoot,
    /// `%gra` tier has multiple ROOT relations.
    #[code("E723")]
    GraMultipleRoots,
    /// `%gra` tier contains a circular dependency.
    #[code("E724")]
    GraCircularDependency,
    /// `%modsyl` tier word count does not match `%mod` tier.
    #[code("E725")]
    ModsylModCountMismatch,
    /// `%phosyl` tier word count does not match `%pho` tier.
    #[code("E726")]
    PhosylPhoCountMismatch,
    /// `%phoaln` tier word count does not match `%mod` tier.
    #[code("E727")]
    PhoalnModCountMismatch,
    /// `%phoaln` tier word count does not match `%pho` tier.
    #[code("E728")]
    PhoalnPhoCountMismatch,
    /// Bullet start time overlaps with previous tier's end time (CLAN Error 84).
    ///
    /// Current tier's BEG is less than the previous tier's END, indicating
    /// overlapping timing. Unlike speaker self-overlap (E704), this applies
    /// across different speakers.
    #[code("E729")]
    #[status(planned)]
    BulletOverlap,
    /// Bullet timing gap exceeds threshold (CLAN Error 85).
    ///
    /// Gap between current tier's BEG and previous tier's END exceeds the
    /// acceptable discontinuity threshold. Only reported in bullet consistency
    /// mode (`+c0`).
    #[code("E730")]
    #[status(planned)]
    BulletGap,
    /// Speaker's bullet start time is before their own previous bullet end time
    /// (CLAN Error 133).
    ///
    /// Supplements the overlap-marker-based E704 with actual bullet timing
    /// check for same-speaker self-overlap.
    #[code("E731")]
    #[status(planned)]
    SpeakerBulletSelfOverlap,
    /// Missing bullet on tier when bullet consistency mode is active (CLAN Error 110).
    ///
    /// When `+c0` or `+c1` is specified, every main tier must have timing.
    #[code("E732")]
    #[status(planned)]
    MissingBullet,
    /// `%mod` tier has fewer words than main tier.
    ///
    /// The model-phonology tier (`%mod`) has fewer alignable tokens than the
    /// main-tier words. Each main-tier word must have a corresponding `%mod`
    /// token. This code is separate from E714 (`%pho`) because the two tiers
    /// represent distinct phonological layers.
    #[code("E733")]
    ModCountMismatchTooFew,
    /// `%mod` tier has more words than main tier.
    ///
    /// The model-phonology tier (`%mod`) has more alignable tokens than the
    /// main-tier words. Remove the extra `%mod` tokens so counts match.
    /// This code is separate from E715 (`%pho`) for the same reason as E733.
    #[code("E734")]
    ModCountMismatchTooMany,
    /// A `%xmodsyl` / `%xphosyl` syllabification unit is not a `phone:CODE` pair.
    ///
    /// A unit must be one IPA phone, an ASCII `:`, then a single constituent
    /// code. A unit with no `:`, an empty phone, or an empty code is invalid.
    #[code("E735")]
    SylUnitMalformed,
    /// A `%xmodsyl` / `%xphosyl` constituent code is not one of `O N C L R E A D U`.
    ///
    /// `U` (unknown) is legal: Phon emits it when a phone has no concrete
    /// syllable constituent. Boundary (`B`), stress (`S`), word (`W`) and tone
    /// (`T`) are never emitted on the syllabification tiers.
    #[code("E736")]
    SylIllegalConstituentCode,
    /// `%xmodsyl` does not reproduce its `%mod` word.
    ///
    /// Stripping the `:CODE` from every unit and concatenating the phones must
    /// equal the corresponding `%mod` word exactly.
    #[code("E737")]
    ModsylReconstructionMismatch,
    /// `%xphosyl` does not reproduce its `%pho` word.
    ///
    /// Stripping the `:CODE` from every unit and concatenating the phones must
    /// equal the corresponding `%pho` word exactly.
    #[code("E738")]
    PhosylReconstructionMismatch,
    /// A `%xphoaln` alignment pair is malformed.
    ///
    /// Every pair must contain exactly one `↔` with a non-empty side on each
    /// side (use `∅` for a null); a pair of `∅↔∅` is invalid.
    #[code("E739")]
    PhoalnPairMalformed,
    /// `%xphoaln` model sides do not reproduce the `%mod` word.
    ///
    /// Concatenating the left element of each pair, skipping `∅`, must equal the
    /// corresponding `%mod` word exactly.
    #[code("E740")]
    PhoalnModReconstructionMismatch,
    /// `%xphoaln` actual sides do not reproduce the `%pho` word.
    ///
    /// Concatenating the right element of each pair, skipping `∅`, must equal the
    /// corresponding `%pho` word exactly.
    #[code("E741")]
    PhoalnPhoReconstructionMismatch,
    /// A `%xphoint` time bullet has `start >= end`.
    ///
    /// Each phone interval's start offset must be strictly less than its end.
    #[code("E742")]
    XphointBulletInvalid,
    /// `%xphoint` interval start times are not non-decreasing.
    ///
    /// Each interval's start must be greater than or equal to the previous
    /// interval's start across the whole tier.
    #[code("E743")]
    XphointIntervalNotMonotonic,
    /// `%xphoint` intervals fall outside the record's media interval.
    ///
    /// The first interval's start and last interval's end must lie within the
    /// `*SPK:` line's media bullet (subject to 1 ms rounding tolerance).
    #[code("E744")]
    XphointMediaBoundsViolation,
    /// `%xphoint` group phones do not reproduce the `%pho` word.
    ///
    /// Concatenating a group's phones, in order, must equal the corresponding
    /// `%pho` word exactly.
    #[code("E745")]
    XphointPhoneReconstructionMismatch,
    /// `%xphoint` group count does not match the `%pho` word count.
    ///
    /// There must be exactly one ` / `-separated group per `%pho` word.
    #[code("E746")]
    XphointGroupCountMismatch,
    /// A blank line in the transcript.
    ///
    /// CHAT does not allow blank lines anywhere in the transcript (CLAN CHECK
    /// 91). The grammar represents a blank line as a structural `blank_line`
    /// node (the single-break `newline` token no longer fuses consecutive
    /// newlines), so the parser emits this from the tree, not by scanning the
    /// source text.
    #[code("E747")]
    BlankLineNotAllowed,
    /// A media bullet timestamp written with a leading zero before another
    /// digit (e.g. `\u{15}012_200\u{15}`).
    ///
    /// Bullet times are plain millisecond integers; CLAN CHECK rejects a
    /// component matching `0[0-9]` as an "Illegal time representation inside
    /// a bullet." (CHECK 90). A bare `0` component is legal. Detected at
    /// parse time because the leading zero exists only in the source text
    /// (the model stores `u64` milliseconds); the bullet's numeric value
    /// still parses, so the AST keeps the bullet while the diagnostic makes
    /// the file invalid.
    #[code("E748")]
    LeadingZeroBulletTime,
    /// A comma glued to the word that follows it (`hey ,you`).
    ///
    /// A comma on a speaker tier must be followed by a space or
    /// end-of-line (CLAN CHECK 92). Detected by span adjacency over the
    /// in-order content walk: the rule fires only when the next item is
    /// a word starting at the byte immediately after the comma, so
    /// exempt constructs that put any other character there (group `<`,
    /// overlap and CA marks) are naturally not flagged.
    #[code("E749")]
    CommaGluedToNextWord,
    /// A space directly after the opening `<` or directly before the
    /// closing `>` of an angle-bracket group (`< dog>` / `<dog >`).
    ///
    /// Group delimiters hug their content (CLAN CHECK 160). The grammar
    /// tolerates the whitespace as an explicit optional `whitespaces`
    /// CST node so the parse recovers; this diagnostic marks the file
    /// invalid instead of silently dropping the space (which also
    /// silently rewrote the text on normalize).
    #[code("E750")]
    SpaceInsideAngleGroup,
    /// A pause marker glued to the end of the preceding word
    /// (`hello(.)`).
    ///
    /// Pauses are free-standing, space-delimited items (CLAN CHECK 57).
    /// Detected by span adjacency over the in-order content walk: the
    /// pause's span starts at the byte where the previous word's span
    /// ends.
    #[code("E751")]
    PauseGluedToWord,
    /// Transcript carries timing evidence (main-tier bullets or a
    /// positional `%wor` timing sidecar) but no `@Media` header declares
    /// the media timeline the timestamps index. Inverse direction of
    /// [`MediaLinkageWithoutTiming`](Self::MediaLinkageWithoutTiming)
    /// (E544); corresponds to CLAN CHECK error 112.
    #[code("E752")]
    TimingWithoutMedia,
    /// Word consists only of a repetition segment: every material part
    /// sits inside `↫...↫` (U+21AB) segment-repetition delimiters with no
    /// stem outside. The notation marks a repeated segment OF a word, so
    /// a fully wrapped word asserts a repetition of nothing. Adopted from
    /// GUI CLAN CHECK error 151 as a chatter-authority rule; a
    /// word-category prefix marker (`&-` filler etc.) counts as a stem.
    #[code("E753")]
    WordOnlyRepetitionSegments,
    /// A `[- CODE]` utterance-level language is not declared in
    /// `@Languages`. Utterance-level presence is substantial, unlike a
    /// word-level `@s:CODE` insertion, which deliberately carries no
    /// declaration requirement (2026-07-15 ruling). Matches CLAN CHECK
    /// error 152.
    #[code("E755")]
    UndeclaredUtteranceLanguage,
    /// User-defined `%x` tier has empty or whitespace-only content: the
    /// line declares an annotation that is not there. Formerly W601 (which
    /// fired as a hard error despite the warning prefix); renumbered
    /// 2026-07-16, rejection unchanged.
    #[code("E756")]
    EmptyDependentTier,
    /// Bracketed code's closing `]` glued to the following content with
    /// no space (`hello [/]x`). Style rule; the parse is unambiguous but
    /// codes are free-standing space-delimited items. Matches CLAN CHECK
    /// error 19.
    #[code("E757")]
    CodeGluedToFollowingContent,
    /// Space between the tier's tab delimiter and the first content item
    /// in a file WITHOUT `@Options: CA` (`*CHI:<tab><space>dog .`). CA
    /// transcripts legitimately column-align with spaces after the tab
    /// (all 457 wild occurrences are CA files, 2026-07-16 scan), so the
    /// CA option exempts the rule. Matches CLAN CHECK error 123.
    #[code("E758")]
    LeadingSpaceOnMainTier,
    /// Utterance content begins with a postfix annotation (retrace,
    /// overlap marker, replacement, or quotation code): the code scopes
    /// over PRECEDING material, and there is none, so the parse is
    /// genuinely broken and the error analysis names it instead of
    /// falling through to the E316 catch-all. Matches CLAN CHECK
    /// error 52 ("Item '%s' must be preceded by text.").
    #[code("E759")]
    AnnotationAtUtteranceStart,
    /// `%mor` item beginning with the `|` separator (`|we`): the
    /// part-of-speech field is empty, which is never meaningful %mor
    /// content. Modern reading of CLAN CHECK error 11 ("Symbol is not
    /// declared in the depfile."): the invariant is a non-empty symbol
    /// before the pipe, not the legacy depfile mechanism.
    #[code("E760")]
    MorItemEmptyPos,
    /// `%gra` relation label whose HEAD is not one of Universal
    /// Dependencies' 37 universal relations (`13|3|PUNCTT`, `4|2|IOB`).
    ///
    /// A label is `HEAD` or `HEAD-SUBTYPE`. UD fixes the head set and
    /// deliberately leaves subtypes open and language-specific, so the
    /// head is the only part of a label checkable against a closed
    /// vocabulary; subtypes are never checked.
    ///
    /// Nothing validated relation labels before, in chatter or in CLAN
    /// CHECK, so a corrupted label rode silently into every downstream
    /// analysis. Grounding for the closed set (full-corpus survey,
    /// 2026-07-26, 106,158 files, 138,565,864 relation instances): all
    /// 37 universal heads are attested, 150 distinct labels occur, and
    /// exactly three heads fall outside the set, `IOB` (146, a
    /// truncation of `IOBJ`), `PAD` (5), and `PUNCTT` (1). Every
    /// language-specific subtype passes untouched.
    #[code("E761")]
    GraRelationHeadNotUniversal,
    /// The prefix marker `#` stands alone as a main-tier word, or opens
    /// one (`# dog`, `#dog`).
    ///
    /// The marker attaches to the END of the prefix it marks (`ha# kelev`),
    /// so neither position can be that construct, and `#` is not a word.
    /// Language-independent: no language writes either shape. Zero
    /// attestations corpus-wide (typed survey, 2026-07-26, over every
    /// `#`-bearing file), so nothing legitimate is affected.
    #[code("E762")]
    PrefixMarkerIllegalPosition,
    /// Legally-positioned prefix marker `#` on a word whose RESOLVED
    /// language does not use the marker (`sun#`, `sun#shine` in an
    /// English utterance).
    ///
    /// What is gated is the marker's PRESENCE in the word, not its
    /// position, exactly as the digits rule (`E220`) gates the presence
    /// of a digit. Position is [`PrefixMarkerIllegalPosition`]'s
    /// concern, and a word rejected there is not reported here too.
    ///
    /// Gated on the word's own computed language, again like `E220`,
    /// never on the file's `@Languages` header: a language-marked word
    /// carries its own language. Grounding (typed survey, 2026-07-26):
    /// 70,654 of 70,668 attestations are Hebrew or Arabic; the
    /// remaining 14 are strays in seven other languages.
    ///
    /// [`PrefixMarkerIllegalPosition`]: Self::PrefixMarkerIllegalPosition
    #[code("E763")]
    PrefixMarkerLanguageNotAllowed,
    /// A `&`-prefixed form runs directly into the preceding word
    /// (`dog&-um`, `dog&~gaga`, `dog&+fr`).
    ///
    /// `&` cannot continue a word, so the shape parses as TWO words: the
    /// missing space silently manufactures a word boundary that the
    /// transcriber did not write and no other diagnostic reports. Style
    /// rule in the [`PauseGluedToWord`] / [`CodeGluedToFollowingContent`]
    /// family: the parse is unambiguous, which is exactly why the source
    /// must be canonically spaced.
    ///
    /// Glued omission (`dog0is`) is a different shape and is not this
    /// code: `0` is ordinary word text, so it yields ONE malformed word,
    /// already rejected by `E220`.
    ///
    /// Juxtaposition-matrix cell 6, ruled REJECT 2026-07-18. Zero
    /// main-tier attestations in the kept corpus at adoption.
    ///
    /// [`PauseGluedToWord`]: Self::PauseGluedToWord
    /// [`CodeGluedToFollowingContent`]: Self::CodeGluedToFollowingContent
    #[code("E764")]
    PrefixedFormGluedToPrecedingWord,
    /// A separator, pause, or overlap marker runs directly into the item
    /// after it (`:and`, `;;`, `(.)dog`, `⌈⌉`).
    ///
    /// Each is a free-standing main-tier item, so the next item takes a
    /// space. Only this direction is invalid: trailing glue ONTO a word
    /// (`word↘`, `dog,`) is documented CHAT convention, and a word glued
    /// to a colon (`dog:`) is not two items at all (the colon fuses as
    /// prosodic lengthening).
    ///
    /// Comma shapes keep their own codes and are not reported here too:
    /// `,dog` is `E749`, `,,` is `E258`.
    ///
    /// Juxtaposition-matrix cell 7, ruled REJECT 2026-07-18. The
    /// following-side-only scope comes from the per-variant probe
    /// (2026-07-29): every `Separator` variant accepted glue on both
    /// sides beforehand, and all the ruled exceptions are trailing, so a
    /// class-level rule would have rejected 30,790 attested CA arrow
    /// usages.
    #[code("E765")]
    SeparatorGluedToFollowingContent,
    /// A linker (`+"`, `++`, `+<`, `+^`, `+,`, `+≈`, `+≋`) placed after
    /// utterance content. Linkers are utterance-initial by definition
    /// (they connect this utterance to the PREVIOUS one), so a linker in
    /// content position is meaningless.
    ///
    /// The grammar deliberately parses the misplaced linker into the CST
    /// (same strict+catch-all pattern as [`IllegalCurlyQuote`]) so this
    /// named rule can locate it precisely; before that, the construct
    /// fell into ERROR-node recovery and surfaced as a generic `E316`
    /// that gave the transcriber nothing to act on (IISRP residue
    /// finding 5, 2026-07-30).
    ///
    /// [`IllegalCurlyQuote`]: Self::IllegalCurlyQuote
    #[code("E766")]
    LinkerNotUtteranceInitial,
    /// Whitespace between the `@Media` filename and the comma after it.
    ///
    /// The comma separates the filename from the media type, so the filename
    /// ends where the comma begins. Real CLAN rejects the space too (CHECK
    /// 148), and an unambiguous style violation still follows CHECK as an
    /// error.
    ///
    /// The construct parses deliberately, so this rule can name it and point at
    /// the space. Before 2026-08-05 the header simply failed to match and the
    /// failure surfaced as [`UnknownHeader`] plus a "Missing media_type node"
    /// complaint about a line that visibly ended in `, audio`: fallout rather
    /// than a judgment, and misleading twice over.
    ///
    /// [`UnknownHeader`]: Self::UnknownHeader
    #[code("E767")]
    MediaWhitespaceBeforeComma,
    /// `@Media` filename cannot be written to a header and read back
    /// unchanged.
    ///
    /// The problems are enumerated once, by `MediaFilenameProblem`; naming a
    /// subset here is how this comment went stale on its first commit.
    /// Unreachable through either parser, which stop the filename at the
    /// comma; the reachable path is a `ChatFile` deserialized from JSON.
    #[code("E768")]
    MediaFilenameNotRepresentable,
    /// Unknown or unrecognized error code (fallback).
    #[code("E999")]
    #[status(planned)]
    UnknownError,
    /// Speaker code not found in `@Participants` (non-fatal).
    #[code("W108")]
    SpeakerNotFoundInParticipants,
}
