//! Stable fingerprint of the active validation rule set.
//!
//! # Why this exists
//!
//! The validation-result cache (`talkbank-cache`) stores a pass/fail verdict
//! keyed on file content. For that cache to be sound, its key must also
//! capture *which validation rules produced the verdict*. Otherwise, when the
//! rule set changes (a new code such as E370 "retrace marker must be followed
//! by material" is added), a stale "Valid" entry from the old rules keeps being
//! served, silently undermining `chatter validate` (the authority on CHAT
//! validity). See the regression test
//! `talkbank-cache/tests/rules_version_invalidation.rs`.
//!
//! [`validation_rules_fingerprint`] derives a stable identifier from two
//! things: the full set of [`ErrorCode`] variants the validator can emit,
//! and a build-time hash of this crate's entire `src/` tree
//! ([`MODEL_BEHAVIOR_FINGERPRINT`], generated by `build.rs`). Adding,
//! removing, or renaming a code changes the fingerprint; so does any edit to
//! a validation predicate, a serialization routine, or anything else in this
//! crate's source, even when no code is added or removed.
//!
//! # The bug this fixes
//!
//! The codes ENUMERATE which checks exist; they do not say what any check
//! DOES. A fingerprint over code names alone is blind to a predicate that
//! tightens or loosens without a code being added or removed, so a cached
//! "Valid" verdict from before the change kept being served after it. The
//! v0.5.x removal of the CA-notation validation exemptions was exactly that
//! shape, and so is any change to serialization (roundtrip verdicts are
//! cached under the same version). Between releases, which is exactly what
//! the fleet runs (chatter is deployed from `main` builds, not only tagged
//! releases), that gap was live.
//!
//! # Why the whole crate, not just the validation submodule
//!
//! Validation predicates are not confined to a `validation` module: for
//! example a main-tier language-switch predicate lives alongside the
//! content model itself. The input sets for "validation behaviour" and
//! "serialization behaviour" are genuinely entangled in this crate, so
//! splitting them into two fingerprints would produce two numbers that are
//! each wrong, rather than one that is honest. Hashing the whole `src/` tree
//! deliberately OVER-invalidates: a comment-only edit anywhere in the crate
//! also changes the fingerprint and evicts the cache. That is the accepted
//! tradeoff: a spurious cache miss costs a few seconds of re-validation; a
//! stale verdict costs correctness, silently. Do not "optimise" this back
//! down to a narrower file set without re-solving that tradeoff.
//!
//! # What this still does not cover
//!
//! Parse behaviour is out of scope here, and deliberately stays that way.
//! The grammar lives in the separate `tree-sitter-talkbank` crate, and
//! `talkbank-cache` depends only on `talkbank-model`, so a grammar-level
//! fingerprint cannot reach the cache from this module without inverting
//! the crate layering. A grammar change that alters what parses (without
//! also touching `talkbank-model`'s own source) will NOT change THIS
//! fingerprint.
//!
//! That gap is closed one layer up, without inverting anything:
//! `talkbank_cache::RulesVersion::current_with_config` takes a parser
//! fingerprint (`talkbank_parser::GRAMMAR_FINGERPRINT`) as a mandatory
//! parameter, supplied by a caller that already depends on both the parser
//! crate and `talkbank-cache` (the CLI, and the desktop app via
//! `talkbank-transform`'s re-export). This module's job stops at the
//! validation-rule dimension; see `talkbank-cache/src/rules_version.rs` for
//! the composed value.
//!
//! # Related CHAT Manual Sections
//!
//! - <https://talkbank.org/0info/manuals/CHAT.html#File_Format>

use super::generated_error_code::ErrorCode;

// Generated by `build.rs`: `pub const MODEL_BEHAVIOR_FINGERPRINT: &str`, a
// hash of this crate's entire `src/` tree (path + contents of every file,
// sorted by relative path). See the module doc comment above.
include!(concat!(env!("OUT_DIR"), "/model_behavior_fingerprint.rs"));

/// FNV-1a 64-bit offset basis.
///
/// We use FNV-1a rather than `std::hash::DefaultHasher` because the latter's
/// output is explicitly NOT stable across Rust versions or process runs in the
/// general case; a cache-compatibility fingerprint must be reproducible so that
/// two builds of chatter with the *same* rule set agree on the same key.
const FNV_OFFSET_BASIS: u64 = 0xcbf2_9ce4_8422_2325;

/// FNV-1a 64-bit prime.
const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;

/// A unit separator byte mixed between codes so that the boundary between two
/// adjacent codes is itself part of the hashed stream. Without it, the streams
/// `["E1", "23"]` and `["E12", "3"]` would hash identically; with it they do
/// not. Value `0x1F` is ASCII Unit Separator, which never appears in a code.
const CODE_SEPARATOR: u8 = 0x1F;

/// Fold one byte into an FNV-1a accumulator.
const fn fnv1a_byte(mut hash: u64, byte: u8) -> u64 {
    hash ^= byte as u64;
    hash = hash.wrapping_mul(FNV_PRIME);
    hash
}

/// Compute a stable fingerprint of the entire validation rule set.
///
/// The fingerprint is a lowercase hex string of an FNV-1a hash over two
/// components, in order:
///
/// 1. Every [`ErrorCode`]'s canonical short code (e.g. `"E370"`), in
///    declaration order, each followed by a `CODE_SEPARATOR`. Declaration
///    order is fixed by the `ErrorCode` enum, so the same code set always
///    contributes the same bytes, and any edit to the code list (new
///    variant, removed variant, renamed code string) changes the result.
/// 2. `MODEL_BEHAVIOR_FINGERPRINT`, the build-time hash of this crate's
///    entire `src/` tree (see the module doc comment). This is what makes
///    the fingerprint change when a rule's PREDICATE changes without its
///    code being added or removed.
///
/// The code-name pass is kept even though it is a subset of what the
/// behaviour fingerprint already covers (a renamed `ErrorCode::as_str()`
/// value is a source change too): it protects against the unlikely case
/// where two source-level changes cancel out in the whole-tree hash while a
/// code string still changed.
///
/// This is intentionally cheap and allocation-light: it walks the `'static`
/// slice from [`ErrorCode::all`] and returns a short hex token suitable for
/// folding into a cache-compatibility version. It is NOT a cryptographic hash;
/// it only needs to change reliably when the rule set changes, not to resist
/// adversarial collision.
pub fn validation_rules_fingerprint() -> String {
    let mut hash = FNV_OFFSET_BASIS;
    for code in ErrorCode::all() {
        for byte in code.as_str().bytes() {
            hash = fnv1a_byte(hash, byte);
        }
        hash = fnv1a_byte(hash, CODE_SEPARATOR);
    }
    for byte in MODEL_BEHAVIOR_FINGERPRINT.bytes() {
        hash = fnv1a_byte(hash, byte);
    }
    format!("{hash:016x}")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The fingerprint must observe what the rules DO, not merely which rules
    /// exist.
    ///
    /// Hashing the code-name list catches a code being added or removed, and
    /// nothing else. A rule whose predicate tightened, with no code added or
    /// removed, produces different verdicts under the same fingerprint, so the
    /// cache keeps serving the old verdict. The v0.5.x CA-exemption removal was
    /// exactly that shape, and so is any grammar change that alters what parses.
    ///
    /// This test pins the distinction by recomputing the old code-names-only
    /// algorithm and requiring the real fingerprint to differ from it.
    #[test]
    fn fingerprint_observes_more_than_the_code_name_list() {
        let names_only = {
            let mut hash = FNV_OFFSET_BASIS;
            for code in ErrorCode::all() {
                for byte in code.as_str().bytes() {
                    hash = fnv1a_byte(hash, byte);
                }
                hash = fnv1a_byte(hash, CODE_SEPARATOR);
            }
            format!("{hash:016x}")
        };

        assert_ne!(
            validation_rules_fingerprint(),
            names_only,
            "the fingerprint still hashes only code names, so a change to what \
             a rule DOES cannot invalidate a cached verdict"
        );
    }

    /// The fingerprint is deterministic: the same rule set hashes identically
    /// every time it is computed.
    #[test]
    fn fingerprint_is_deterministic() {
        assert_eq!(
            validation_rules_fingerprint(),
            validation_rules_fingerprint(),
            "fingerprint must be stable across calls within a build"
        );
    }

    /// The fingerprint actually depends on the code set: hashing a list that
    /// drops a code (simulating "before E370 was added") must differ from the
    /// real fingerprint. This is the property the cache relies on.
    #[test]
    fn fingerprint_changes_when_a_code_is_added_or_removed() {
        // Recompute the fingerprint over the full set, but skip E370. If the
        // hash ignored the code list this would equal the real fingerprint.
        let mut hash = FNV_OFFSET_BASIS;
        for code in ErrorCode::all() {
            if *code == ErrorCode::StructuralOrderError {
                continue; // pretend E370 does not exist yet
            }
            for byte in code.as_str().bytes() {
                hash = fnv1a_byte(hash, byte);
            }
            hash = fnv1a_byte(hash, CODE_SEPARATOR);
        }
        let without_e370 = format!("{hash:016x}");

        assert_ne!(
            without_e370,
            validation_rules_fingerprint(),
            "removing a validation code must change the rules fingerprint"
        );
    }
}
