const test = require("node:test");
const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { join } = require("node:path");

// Drift guard for the Tauri updater wiring in tauri.conf.json. The runtime
// auto-update behavior cannot be exercised without a signing key and a real
// release, so this test pins the configuration that drives it: if any of these
// keys is dropped or renamed, updates silently stop shipping. Read the raw
// config rather than a generated artifact so it catches hand-edits.
function tauriConfig() {
  const path = join(__dirname, "..", "..", "src-tauri", "tauri.conf.json");
  return JSON.parse(readFileSync(path, "utf8"));
}

test("bundle is configured to emit updater artifacts", () => {
  const config = tauriConfig();
  assert.equal(
    config.bundle.createUpdaterArtifacts,
    true,
    "bundle.createUpdaterArtifacts must be true so signed update bundles are produced",
  );
});

test("the updater plugin points at the GitHub Releases latest.json endpoint", () => {
  const config = tauriConfig();
  const updater = config.plugins?.updater;
  assert.ok(updater, "plugins.updater must be configured");
  assert.ok(
    Array.isArray(updater.endpoints) && updater.endpoints.length > 0,
    "plugins.updater.endpoints must be a non-empty array",
  );
  assert.ok(
    updater.endpoints.some(
      (url) =>
        url.includes("github.com/TalkBank/chatter") &&
        url.includes("latest.json"),
    ),
    `endpoints must include the GitHub Releases latest.json: ${JSON.stringify(updater.endpoints)}`,
  );
});

test("the updater plugin carries a public key for signature verification", () => {
  const config = tauriConfig();
  const pubkey = config.plugins?.updater?.pubkey;
  assert.equal(typeof pubkey, "string");
  assert.ok(
    pubkey.length > 0,
    "plugins.updater.pubkey must be set (the real key is generated by the maintainer before release)",
  );
});
