//! The `ErrorCode` enum, emitted from the per-code registry.
//!
//! # R1 of the spec-system redesign, and what it deletes
//!
//! `ErrorCode` was hand-written beside `spec/errors/`, so every per-code fact
//! existed twice and four checks stood where an owner belongs:
//!
//! - `SpecStatusGate` reconciled `#[status(planned)]` against each spec's
//!   `status`, in both directions, and was 180 lines. It is deleted: the
//!   attribute is now emitted FROM the status.
//! - `build_diagnostic_kind` refused to run when a variant had no spec file or
//!   a spec named no variant. Two vocabularies met there and it was the join.
//!   There is one vocabulary now.
//! - The same function required every spec file for a code to agree about
//!   `kind`, because `kind` was copied into each of them.
//! - A 20-line comment in the enum asked readers not to reuse a retired
//!   number. `CodeRegistry` refuses the file instead.
//!
//! # The bootstrap, stated because it is a real property
//!
//! This generator does NOT link `talkbank-model`, so it can rebuild the enum
//! from the registry even when the committed enum does not compile. What it
//! cannot do is repair a generator bug: the recovery from generated source
//! that will not build is `git checkout` of the generated file, exactly as for
//! `generated_diagnostic_kind.rs`. The registry's own types make the ordinary
//! authoring mistakes unreachable, which is why that is an acceptable
//! backstop rather than the main defence: [`VariantName`] cannot hold a token
//! that is not an identifier, and [`Rustdoc`] cannot hold an empty one.
//!
//! [`VariantName`]: talkbank_spec_vocabulary::registry::VariantName
//! [`Rustdoc`]: talkbank_spec_vocabulary::registry::Rustdoc

use std::fmt::Write as _;

use crate::rust_source::doc_comment;
use talkbank_spec_vocabulary::registry::{CodeEntry, CodeRegistry};

/// The file this generator writes inside the model's `codes` module.
pub const OUTPUT_FILE: &str = "generated_error_code.rs";

/// Render the complete `ErrorCode` source from the registry.
///
/// Unformatted: the caller runs it through
/// [`crate::rust_source::format_generated_rust`], which is the one owner of
/// that step for every Rust artifact.
#[must_use]
pub fn render(registry: &CodeRegistry) -> String {
    let mut out = String::new();
    out.push_str(HEADER);

    // Retired numbers ride along as a comment on the generated file rather
    // than as code. They are not variants and must never become variants; the
    // ENFORCEMENT is `CodeRegistry`'s refusal to register one, and this is a
    // courtesy to a reader who arrives at the enum first.
    if !registry.retired().is_empty() {
        out.push_str(
            "// RETIRED numbers, never reused. Enforced by the registry, which \
             refuses\n// to register one; listed here for a reader who reaches \
             the enum first.\n",
        );
        for retired in registry.retired() {
            let _ = writeln!(out, "// {}: {}", retired.code, retired.reason);
        }
        out.push('\n');
    }

    out.push_str(ENUM_DOC);
    out.push_str("#[talkbank_derive::error_code_enum]\npub enum ErrorCode {\n");
    for entry in registry.entries() {
        push_variant(&mut out, entry);
    }
    out.push_str("}\n");
    out
}

/// One variant: its rustdoc, its code, and its enforcement attribute.
///
/// The doc goes through [`doc_comment`], which is the one owner of "a blank
/// line is a paragraph break". This inlined that rule with a hardcoded
/// four-space indent, which was wasted twice over: the helper already existed
/// in this crate, and [`format_generated_rust`] re-indents doc comments from
/// scratch, so the indentation was written, reviewed and then discarded.
///
/// The line-by-line shape itself is load-bearing. A single `writeln!` of the
/// whole doc was correct only while `Rustdoc` refused newlines, and refusing
/// them flattened the multi-paragraph docs several codes carry;
/// `schema/chat-file.schema.json` embeds every variant's doc verbatim, and is
/// what noticed.
///
/// [`format_generated_rust`]: crate::rust_source::format_generated_rust
fn push_variant(out: &mut String, entry: &CodeEntry) {
    out.push_str(&doc_comment(entry.rustdoc().lines()));
    let _ = writeln!(out, "\n#[code(\"{}\")]", entry.code());
    // ONE owner for "which statuses mean the check does not run". It was the
    // deleted gate's `as_check_status`, whose policy is now `Status::is_enforced`.
    if !entry.status().is_enforced() {
        out.push_str("#[status(planned)]\n");
    }
    let _ = writeln!(out, "{},", entry.variant());
}

/// The generated file's own module doc.
const HEADER: &str = "\
//! Canonical diagnostic code enum for TalkBank parsing/validation.
//!
//! GENERATED by `spec_gen` from `spec/codes/error-codes.toml`.
//! DO NOT EDIT BY HAND: change the registry.
//!
//! Regenerate with `just spec-gen`; `just spec-check` reports whether this
//! copy is current without writing anything.
//!
//! Each variant's rustdoc is the registry's `summary`, and `#[status(planned)]`
//! is emitted from its `status`, so the enum cannot disagree with the specs
//! about which checks run. The gate that used to reconcile the two is gone.
//!
//! # Related CHAT Manual Sections
//!
//! - <https://talkbank.org/0info/manuals/CHAT.html#File_Format>

";

/// The enum's own doc comment, which is about the TYPE rather than about any
/// code, and so is the generator's to write.
const ENUM_DOC: &str = "\
/// Standard error codes for CHAT parsing and validation.
///
/// The `#[error_code_enum]` attribute macro derives, from the `#[code(\"...\")]`
/// attributes below: the serde renames, `as_str`, `parse_exact`,
/// `Display`, `documentation_url`, `iter` and `planned`. The attributes
/// themselves come from `spec/codes/error-codes.toml`, so the code strings, the
/// variant names and the enforcement split all have one owner and no gate
/// standing between two copies of them.
///
/// See [`super::CheckStatus`] for the enforced/planned distinction and
/// [`ErrorCode::check_status`] for reading it off a value.
";

#[cfg(test)]
mod tests {
    use super::render;
    use talkbank_spec_vocabulary::registry::CodeRegistry;

    fn registry() -> CodeRegistry {
        CodeRegistry::parse(
            "[[retired]]\ncode = 'W601'\nreason = 'renumbered to E756'\n\
             [[code]]\ncode = 'E001'\nvariant = 'InternalError'\n\
             summary = 'Internal error.'\nkind = 'Invalidity'\n\
             status = 'implemented'\n\
             [[code]]\ncode = 'E003'\nvariant = 'EmptyString'\n\
             summary = 'Input string is empty.'\nkind = 'Invalidity'\n\
             status = 'not_implemented'\n",
        )
        .expect("well-formed")
    }

    /// The attribute is emitted from the STATUS, which is the whole of R1's
    /// first deletion: there is no second copy for a gate to reconcile.
    #[test]
    fn only_a_not_implemented_status_is_marked_planned() {
        let source = render(&registry());
        let implemented = source
            .split("InternalError")
            .next()
            .expect("text before the first variant");
        assert!(
            !implemented.ends_with("#[status(planned)]\n"),
            "an implemented code must not be marked planned:\n{source}"
        );
        assert!(
            source.contains("#[status(planned)]\nEmptyString,"),
            "a not_implemented code must be marked planned:\n{source}"
        );
    }

    /// Retired numbers reach the reader who arrives at the enum first, with
    /// the reason the registry recorded.
    #[test]
    fn retired_numbers_are_listed_with_their_reasons() {
        let source = render(&registry());
        assert!(source.contains("// W601: renumbered to E756"), "{source}");
    }

    /// A wire-format property of the emitted text: the summary becomes the
    /// variant's rustdoc, which is what puts a placeholder description
    /// somewhere embarrassing enough to get fixed.
    #[test]
    fn the_summary_becomes_the_variants_rustdoc() {
        let source = render(&registry());
        assert!(
            source.contains("/// Input string is empty.\n#[code(\"E003\")]"),
            "{source}"
        );
    }

    /// A paragraph break survives into the emitted source as a bare `///`.
    ///
    /// The regression this pins: emitting the doc with one `writeln!` turned
    /// every multi-paragraph rustdoc into a run-on sentence, and it reached
    /// `schema/chat-file.schema.json` before anything noticed.
    #[test]
    fn a_paragraph_break_emits_as_a_bare_doc_line() {
        let toml = [
            "[[code]]",
            "code = 'E001'",
            "variant = 'InternalError'",
            "summary = \"First.\\n\\nSecond.\"",
            "kind = 'Invalidity'",
            "status = 'implemented'",
        ]
        .join("\n");
        let source = render(&CodeRegistry::parse(&toml).expect("well-formed"));
        assert!(
            source.contains("/// First.\n///\n/// Second.\n"),
            "{source}"
        );
    }
}
