// Build scripts run at build time, not runtime. Panics here fail
// `cargo build`, which is the intended behaviour for missing files
// or invalid embedded data.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::env;
use std::path::Path;

/// Vendored generated lexer (committed to repo, regenerated by re2rust on macOS).
const VENDORED_LEXER: &str = "src/generated/lexer.rs";

/// Generated Rust file name in OUT_DIR.
const LEXER_RUST_FILE: &str = "lexer.rs";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed={VENDORED_LEXER}");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set by Cargo");
    let out_path = Path::new(&out_dir).join(LEXER_RUST_FILE);

    // Copy the vendored (pre-generated) lexer to OUT_DIR.
    //
    // To regenerate (requires re2c 4.x, `brew install re2c` on macOS):
    //   re2rust -W -Wno-nondeterministic-tags --input-encoding utf8 --utf8 \
    //     --no-generation-date \
    //     --conditions -o src/generated/lexer.rs src/lexer.re
    //
    // `--no-generation-date` is REQUIRED so that regenerating produces a
    // byte-identical file, which is what makes a diff meaningful. Omitting it
    // embeds a timestamp header (`/* Generated by re2rust 4.5.1 on Wed ... */`)
    // and every regeneration then looks like a change.
    //
    // CORRECTION, 2026-08-11: this comment used to say a CI job named "Verify
    // vendored lexer is up to date" re-runs re2rust and byte-diffs the result.
    // NO SUCH JOB EXISTS. No workflow installs re2c, so CI cannot run one, and
    // nothing verifies that the committed lexer matches `lexer.re`. The check
    // is `just verify-vendored-lexer`, which takes about half a second and has
    // to be run by hand after any change to `lexer.re` or to the generated
    // `generated_form_markers.re` it includes. Asserting a gate that does not
    // exist is worse than admitting there is none, because it stops the next
    // reader looking.
    //
    // See lexer.re header comment for why -Wno-nondeterministic-tags is needed.
    std::fs::copy(VENDORED_LEXER, &out_path)?;

    Ok(())
}
