// @generated by `gen_form_markers` (spec/tools) from
// spec/form_markers/form_marker_registry.json. DO NOT EDIT MANUALLY.
//
// Regenerate with `just form-markers-gen`, then regenerate the vendored lexer
// (see build.rs for the exact re2rust invocation) in the same commit.
//
// The closed set of CHAT special-form marker codes, WITHOUT the leading `@`
// and WITHOUT any `:label`. Both of those are spelled out at each use site,
// because the four rules that lex a word tag the marker's boundaries
// differently and only the code itself is common to them.
//
// Note that this set does not decide which codes may take a `:label`: the
// lexer accepts `:label` after any of them and the typed model rejects the
// ones that must not have it (`@x:foo` is E203). Teaching the lexer that
// distinction would move a validity judgement into tokenization, which is the
// opposite of this codebase's parse-don't-validate rule.

w_form_code = "b" | "c" | "d" | "f" | "fp" | "g" | "i" | "k" | "l" | "ls" | "n" | "o"
             | "p" | "q" | "sas" | "si" | "sl" | "t" | "u" | "wp" | "x" | "z";
