// Test code is exempt from this crate's `deny`-level panic lints,
// see `docs/panic-audit/talkbank-parser-re2c.md`.
#![cfg_attr(docsrs, feature(doc_cfg, doc_auto_cfg))]
#![cfg_attr(
    test,
    allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::panic,
        clippy::unreachable,
        clippy::todo,
        clippy::unimplemented
    )
)]
#![deny(missing_docs)]

//! re2c-based CHAT parser and lexer.
//!
//! This crate provides the alternate parser used as an equivalence oracle
//! against the tree-sitter parser. It is a real public parser surface, but its
//! primary job inside the TalkBank workspace is to catch coverage gaps in the
//! specs and reference corpus by disagreeing with the default parser.
//!
//! # Start here
//!
//! - [`Re2cParser`] implements the shared [`talkbank_model::ChatParser`] trait
//! - [`lex`] and [`lex_line`] expose the re2c lexer directly for debugging and
//!   narrow parser tests
//! - [`lexer`] exposes start-condition constants for targeted tier/body lexing
//!
//! Lower-level AST/conversion/test-helper modules remain reachable for this
//! crate's own tests and benchmarks, but they are intentionally hidden from the
//! public docs because they are parser-oracle implementation details rather than
//! first-wave supported entry points.
//!
//! # Example
//!
//! ```rust
//! use talkbank_model::{ChatParser, NullErrorSink};
//! use talkbank_parser_re2c::Re2cParser;
//!
//! let parser = Re2cParser::new();
//! let outcome = parser.parse_chat_file("@UTF8\n@Begin\n*CHI:\thello .\n@End\n", 0, &NullErrorSink);
//! assert!(outcome.into_option().is_some());
//! ```

#[doc(hidden)]
pub mod ast;
#[doc(hidden)]
pub mod chat_lines;
#[doc(hidden)]
pub mod chat_parser_impl;
#[doc(hidden)]
pub mod convert;
pub mod error;
#[doc(hidden)]
pub mod parser;
#[doc(hidden)]
pub mod token;

pub use chat_parser_impl::Re2cParser;

/// Test support utilities (fixture loading, etc.)
#[doc(hidden)]
pub mod tests_support {
    /// Load fixture lines from tests/fixtures/.
    pub fn load_fixture(name: &str) -> Vec<String> {
        let path = format!("{}/tests/fixtures/{name}.txt", env!("CARGO_MANIFEST_DIR"));
        let content = match std::fs::read_to_string(&path) {
            Ok(c) => c,
            Err(_) => return vec![],
        };
        let mut entries = Vec::new();
        let mut current = String::new();
        for line in content.lines() {
            if line.starts_with('#') {
                continue;
            }
            if line.is_empty() {
                if !current.is_empty() {
                    entries.push(std::mem::take(&mut current));
                }
            } else {
                if !current.is_empty() {
                    current.push('\n');
                }
                current.push_str(line);
            }
        }
        if !current.is_empty() {
            entries.push(current);
        }
        entries
    }
}

// Re-export talkbank-model for consumers.
pub use talkbank_model;

use token::LexResult;

/// Lex a line starting from a given condition. Returns `LexResult`
/// with tokens and error-checking utilities.
///
/// The input should be NUL-terminated or will be padded internally.
pub fn lex_line(input: &str, condition: usize) -> LexResult<'_> {
    // Ensure NUL-terminated
    let padded: &str = if input.ends_with('\0') {
        input
    } else {
        let mut s = input.to_string();
        s.push('\0');
        Box::leak(s.into_boxed_str())
    };
    let tokens: Vec<_> = lexer::Lexer::new(padded, condition).collect();
    LexResult { tokens }
}

/// Lex a complete line from INITIAL condition.
pub fn lex(input: &str) -> LexResult<'_> {
    lex_line(input, lexer::COND_INITIAL)
}

/// Include generated lexer.
pub mod lexer {
    // The included file is the re2c-generated DFA (~63k lines). Its
    // single `panic!("internal lexer error")` at the unreachable-by-
    // construction terminal state is intrinsic to re2c's output
    // shape; we cannot annotate it per-site since the file is
    // regenerated by build.rs. Module-level allow.
    #![allow(clippy::panic, clippy::unwrap_used, clippy::expect_used)]

    // Generated lexer.rs will use crate::token::Token directly.
    const NONE: usize = usize::MAX;

    include!(concat!(env!("OUT_DIR"), "/lexer.rs"));

    // Re-export condition constants for start-state-based entry points.
    // Consumers can start the lexer in a specific condition to parse
    // isolated tiers (e.g., %mor body, %gra body, main tier content).
    /// Start condition for top-level line classification (`@`, `*`, `%`).
    pub const COND_INITIAL: usize = YYC_INITIAL;
    /// Start condition for main-tier (`*SPK:`) content.
    pub const COND_MAIN_CONTENT: usize = YYC_MAIN_CONTENT;
    /// Start condition for `%mor` tier content.
    pub const COND_MOR_CONTENT: usize = YYC_MOR_CONTENT;
    /// Start condition for `%gra` tier content.
    pub const COND_GRA_CONTENT: usize = YYC_GRA_CONTENT;
    /// Start condition for `%pho` tier content.
    pub const COND_PHO_CONTENT: usize = YYC_PHO_CONTENT;
    /// Start condition for `%sin` tier content.
    pub const COND_SIN_CONTENT: usize = YYC_SIN_CONTENT;
    /// %wor uses MAIN_CONTENT, same word rules as main tier.
    pub const COND_WOR_CONTENT: usize = YYC_MAIN_CONTENT;
    /// Start condition for generic dependent-tier text content.
    pub const COND_TIER_CONTENT: usize = YYC_TIER_CONTENT;
    /// %com: text_with_bullets_and_pics (adds inline_pic to TIER_CONTENT).
    pub const COND_COM_CONTENT: usize = YYC_COM_CONTENT;
    /// User-defined tiers (%x*): text_with_bullets.
    pub const COND_USER_TIER_CONTENT: usize = YYC_USER_TIER_CONTENT;
    /// Start condition for generic structured-header content.
    pub const COND_HEADER_CONTENT: usize = YYC_HEADER_CONTENT;
    /// Start condition for `@ID` header content.
    pub const COND_ID_CONTENT: usize = YYC_ID_CONTENT;
    /// Start condition for `@Types` header content.
    pub const COND_TYPES_CONTENT: usize = YYC_TYPES_CONTENT;
    /// Start condition for `@Languages` header content.
    pub const COND_LANGUAGES_CONTENT: usize = YYC_LANGUAGES_CONTENT;
    /// Start condition for `@Participants` header content.
    pub const COND_PARTICIPANTS_CONTENT: usize = YYC_PARTICIPANTS_CONTENT;
    /// Start condition for `@Media` header content.
    pub const COND_MEDIA_CONTENT: usize = YYC_MEDIA_CONTENT;
}
