//! Staleness guard for the generated typed CST traversal.
//!
//! `crates/talkbank-parser-tests/src/generated_traversal.rs` is generated by
//! the `tree-sitter-grammar-utils` `generate_traversal` example from this
//! repo's `grammar/src/grammar.json` and `grammar/src/node-types.json` (see the
//! grammar-change workflow in the repo `CLAUDE.md`). The generator stamps a
//! deterministic provenance header recording the SHA-256 of each input file.
//!
//! This test recomputes those digests from the committed grammar JSON and
//! asserts they match the digests embedded in the generated file. If they
//! differ, the grammar changed without regenerating the traversal, so the typed
//! traversal (and the parity tests built on it) no longer reflect the grammar.
//! The fix is to regenerate, never to hand-edit the generated file.
//!
//! This is the cheap, checkout-free half of the staleness guard: it needs only
//! the committed files, not a checkout of `tree-sitter-grammar-utils`.

use std::fmt::Write as _;
use std::path::PathBuf;

use sha2::{Digest, Sha256};

/// Lowercase hex SHA-256, byte-for-byte matching the generator's digest format.
fn sha256_hex(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .fold(String::with_capacity(64), |mut acc, byte| {
            // `write!` to a String is infallible; the result is discarded.
            let _ = write!(acc, "{byte:02x}");
            acc
        })
}

/// Repo root, derived from this crate's manifest dir
/// (`<repo>/crates/talkbank-parser-tests`).
fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
}

/// The two digests embedded in the generated file's provenance header:
/// `(grammar.json sha256, node-types.json sha256)`.
fn embedded_digests(generated: &str) -> (String, String) {
    // One line, shaped:
    //   //! Source grammar digest (sha256): grammar.json=<64hex> node-types.json=<64hex>
    let re = regex::Regex::new(r"grammar\.json=([0-9a-f]{64}) node-types\.json=([0-9a-f]{64})")
        .expect("static digest regex compiles");
    let caps = re.captures(generated).expect(
        "generated_traversal.rs is missing its provenance digest line; regenerate it with the \
         grammar-change workflow (do not hand-edit the generated file)",
    );
    (caps[1].to_owned(), caps[2].to_owned())
}

/// Asserts the committed `generated_traversal.rs` was generated from the current
/// committed grammar JSON. A failure means someone changed `grammar.js` and
/// regenerated `grammar/src/*.json` but did not regenerate the typed traversal.
#[test]
fn generated_traversal_is_current() {
    let root = repo_root();
    let grammar_json = std::fs::read(root.join("grammar/src/grammar.json"))
        .expect("grammar/src/grammar.json is readable");
    let node_types_json = std::fs::read(root.join("grammar/src/node-types.json"))
        .expect("grammar/src/node-types.json is readable");

    let generated = std::fs::read_to_string(
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/generated_traversal.rs"),
    )
    .expect("generated_traversal.rs is readable");

    let (embedded_grammar, embedded_node_types) = embedded_digests(&generated);

    for (input, embedded, actual) in [
        (
            "grammar/src/grammar.json",
            &embedded_grammar,
            sha256_hex(&grammar_json),
        ),
        (
            "grammar/src/node-types.json",
            &embedded_node_types,
            sha256_hex(&node_types_json),
        ),
    ] {
        assert_eq!(
            *embedded, actual,
            "generated_traversal.rs is STALE: {input} changed since it was generated. \
             Regenerate the typed CST traversal (grammar-change workflow step 3) instead of \
             editing the generated file by hand."
        );
    }
}
