#!/usr/bin/env node

// Generates the book's CA and disfluency symbol tables from the registry.
//
// These tables were hand-written until 2026-08-20, when four of their rows were
// found to contradict the enums they were describing: the raised period was
// labelled a micropause (it is inhalation), the not-equal sign was labelled
// inhalation (it is blocking, a disfluency mark), and the increment and nabla
// were labelled pitch registers (they are faster and slower). Nothing could
// notice, because a markdown table is gated by nothing.

const path = require('node:path');
const {
  PARSE_ROLES,
  failWith,
  loadRegistry,
  lookupOrFail,
  writeGenerated,
} = require('./registry.js');

const fail = failWith('book table generation failed');

// Keyed by parse role. The loop below iterates PARSE_ROLES, the closed
// vocabulary registry.js owns and validates every symbol against; it is NOT
// derived from the registry FILE, so adding a role means teaching registry.js
// and then each generator, which fails loudly until taught.
const ROLE_SECTIONS = {
  word_attached: {
    heading: 'Word-attached symbols',
    category: '`ca_element_symbols`',
    blurb: 'These attach to a word, so `book↑` is a single token whose content\ncarries the symbol.',
  },
  paired_stretch: {
    heading: 'Paired delimiter symbols',
    category: '`ca_delimiter_symbols`',
    blurb:
      'These are PAIRED: each opens and closes a stretch, and an unmatched one\nis rejected (E230).',
  },
};

function cell(text) {
  return text.replaceAll('|', '\\|');
}

function render(symbols) {
  const sections = PARSE_ROLES.map((role) => {
    const spec = lookupOrFail(ROLE_SECTIONS, role, 'ROLE_SECTIONS', fail);
    const rows = symbols
      .filter((s) => s.parse_role === role)
      .map((s) => {
        const family = s.notation_family === 'disfluency' ? 'disfluency' : 'CA';
        const example = s.example.replace(/^\*PAR:\t/, '');
        return `| \`${cell(s.char)}\` | ${s.codepoint} | ${cell(s.gloss)} | ${family} | \`${cell(example)}\` |`;
      })
      .join('\n');
    return `### ${spec.heading} (${spec.category})\n\n${spec.blurb}\n\n`
      + '| Symbol | Codepoint | Meaning | Notation | Example |\n'
      + '|--------|-----------|---------|----------|---------|\n'
      + `${rows}\n`;
  }).join('\n');

  return `<!-- @generated by spec/symbols/generate_book_tables.js from
     spec/symbols/symbol_registry.json. DO NOT EDIT MANUALLY.
     Regenerate with \`just symbols-gen\`. -->

The **Notation** column is the symbol's provenance and is independent of which
category it parses into. A symbol marked \`disfluency\` comes from the CHAT
manual's Disfluency Transcription chapter and is not Conversation Analysis
notation; CLAN classifies those explicitly as NOT CA. They sit in the \`ca_*\`
categories purely because of how they parse.

Every example is parsed and validated by a test, so a row here cannot drift
from what the grammar accepts.

${sections}`;
}

function main() {
  const { repoRoot, symbols } = loadRegistry();
  writeGenerated(
    repoRoot,
    path.join(repoRoot, 'book', 'src', 'chat-format', 'generated', 'ca-symbols.md'),
    render(symbols),
  );
}

main();
