#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const REQUIRED_CATEGORY_KEYS = [
  'ca_delimiter_symbols',
  'ca_element_symbols',
  'word_segment_forbidden_start_symbols',
  'word_segment_forbidden_rest_symbols',
  'word_segment_forbidden_common_symbols',
  'event_segment_forbidden_symbols',
  'event_segment_forbidden_common_symbols',
];

function fail(message) {
  console.error(`rust symbol-set generation failed: ${message}`);
  process.exit(1);
}

function rustStringLiteral(s) {
  if (typeof s !== 'string' || s.length === 0) {
    fail(`expected non-empty string, got: ${JSON.stringify(s)}`);
  }

  const cp = s.codePointAt(0);
  if ([...s].length !== 1) {
    fail(`expected single Unicode scalar value, got: ${JSON.stringify(s)}`);
  }

  if (s === '\\') return '"\\\\"';
  if (s === '"') return '"\\\""';
  if (s === '\n') return '"\\n"';
  if (s === '\r') return '"\\r"';
  if (s === '\t') return '"\\t"';
  if (cp < 0x20 || cp === 0x7f || cp === 0x2028 || cp === 0x2029) {
    return `"\\u{${cp.toString(16)}}"`;
  }

  return `"${s}"`;
}

function readRegistry() {
  const repoRoot = path.resolve(__dirname, '..', '..');
  const registryPath = path.join(repoRoot, 'spec', 'symbols', 'symbol_registry.json');
  if (!fs.existsSync(registryPath)) {
    fail(`missing registry file at ${registryPath}`);
  }

  let registry;
  try {
    registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
  } catch (err) {
    fail(`invalid JSON: ${err.message}`);
  }

  if (!registry.categories || typeof registry.categories !== 'object') {
    fail('registry.categories must be an object');
  }

  for (const key of REQUIRED_CATEGORY_KEYS) {
    if (!Array.isArray(registry.categories[key])) {
      fail(`missing or invalid category: ${key}`);
    }
  }

  return { repoRoot, registry };
}

// Format generated Rust with the same tool `cargo fmt` uses.
//
// Without this, two processes claim the same bytes: `just fmt` rewraps these
// const arrays, and re-running the generator unwraps them again, so the two
// disagree forever and each is correct. Running rustfmt here makes "generated"
// and "formatted" one state. Found by adding `--check`, which reported the
// committed file STALE on its first run against an unmodified registry.
//
// Hard failure when rustfmt is missing, deliberately: a generator that skipped
// formatting would emit a file the next `cargo fmt` immediately invalidates.
function rustfmt(source) {
  const result = spawnSync('rustfmt', ['--edition', '2024', '--emit', 'stdout'], {
    input: source,
    encoding: 'utf8',
  });
  if (result.error) {
    fail(`cannot run rustfmt (it ships with the Rust toolchain): ${result.error.message}`);
  }
  if (result.status !== 0) {
    fail(`rustfmt rejected the generated module: ${result.stderr}`);
  }
  return result.stdout;
}

function renderRust(registry) {
  const c = registry.categories;
  const rows = REQUIRED_CATEGORY_KEYS.map((key) => {
    const constName = key.toUpperCase();
    const values = c[key].map(rustStringLiteral).join(', ');
    return `pub const ${constName}: &[&str] = &[${values}];`;
  });

  return rustfmt(`// @generated by spec/symbols/generate_rust_symbol_sets.js\n// DO NOT EDIT MANUALLY.\n\n${rows.join('\n')}\n`);
}

// `--check` renders and COMPARES, writing nothing and exiting non-zero on
// drift. It exists so a test can gate these outputs: the generators write to
// fixed repository paths, so a gate that simply ran them would mutate the tree
// it is checking. Until 2026-08-11 nothing verified these files at all, and a
// hand-edit to a generated symbol set was undetectable.
const CHECK_ONLY = process.argv.includes('--check');

function writeIfChanged(filePath, content) {
  const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
  if (CHECK_ONLY) {
    if (existing !== content) {
      console.error(
        `STALE: ${filePath} does not match spec/symbols/symbol_registry.json. ` +
          'Regenerate with `just symbols-gen`.',
      );
      process.exit(1);
    }
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  if (existing !== content) {
    fs.writeFileSync(filePath, content, 'utf8');
  }
}

function main() {
  const { repoRoot, registry } = readRegistry();
  const content = renderRust(registry);

  const outputs = [
    path.join(repoRoot, 'crates', 'talkbank-model', 'src', 'generated', 'symbol_sets.rs'),
    path.join(repoRoot, 'spec', 'tools', 'src', 'generated', 'symbol_sets.rs'),
  ];

  for (const output of outputs) {
    writeIfChanged(output, content);
    console.log(`${CHECK_ONLY ? 'current' : 'updated'}: ${path.relative(repoRoot, output)}`);
  }
}

main();
