#!/usr/bin/env node

// Emits the Rust character-set constants from the symbol registry.
//
// The emission order is `Object.keys(registry.categories)`, which registry.js
// builds. An earlier cut restated that order here as a const, so the order was
// asserted in two files that had to agree, which is the mirror this registry
// exists to delete.

const path = require('node:path');
const { loadRegistry, rustLiteral, rustfmt, writeGenerated } = require('./registry.js');

function renderRust(categories) {
  const rows = Object.entries(categories).map(
    ([key, values]) =>
      `pub const ${key.toUpperCase()}: &[&str] = &[${values.map(rustLiteral).join(', ')}];`,
  );
  return rustfmt(
    `// @generated by spec/symbols/generate_rust_symbol_sets.js\n// DO NOT EDIT MANUALLY.\n\n${rows.join('\n')}\n`,
  );
}

function main() {
  const { repoRoot, categories } = loadRegistry();
  const content = renderRust(categories);
  for (const output of [
    path.join(repoRoot, 'crates', 'talkbank-model', 'src', 'generated', 'symbol_sets.rs'),
    path.join(repoRoot, 'spec', 'tools', 'src', 'generated', 'symbol_sets.rs'),
  ]) {
    writeGenerated(repoRoot, output, content);
  }
}

main();
