// Test code: the panic-family clippy lints are relaxed by policy
// (assertions and fixture unwraps are the testing idiom); the
// workspace [lints] table holds production code to deny.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::unreachable,
    clippy::todo,
    clippy::unimplemented
)]

//! Test module for generated in `talkbank-chat`.
//!
//! These tests document expected behavior and regressions.

// This file includes all auto-generated test modules from tests/generated/
// Tests in this directory are generated by:
// - bootstrap_spec_examples
// - bootstrap_reference_corpus

// This file IS the `generated` module of the integration binary, so the
// included tests land directly in it; an inner `mod generated` would only
// produce `generated::generated::`.
include!("./generated/reference_corpus.rs");
