//! Build script for the Rust binding of the TalkBank tree-sitter grammar.
//!
//! Compiles generated C sources, enables query-constant cfg flags when query
//! files are present in the crate, and generates a build-time fingerprint of
//! this crate's own sources (`GRAMMAR_FINGERPRINT`) for downstream cache
//! versioning. See [`generate_grammar_fingerprint`]'s doc comment.

// Generated by tree-sitter, suppress lints on template code.
#![allow(clippy::const_is_empty)]
// Build scripts run at build time, not runtime. Panics here fail
// `cargo build`, which is the intended behaviour for missing files or
// unreadable sources. Mirrors the same allowance (and rationale) in
// `crates/talkbank-model/build.rs`.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;

/// FNV-1a 64-bit offset basis.
///
/// Duplicated from `crates/talkbank-model/build.rs` (which duplicates it
/// again from `crates/talkbank-model/src/errors/codes/rules_fingerprint.rs`)
/// rather than shared: a build script cannot depend on the crate it builds,
/// and this crate has no other TalkBank crate as a dependency to share it
/// with either. Two lines of algorithm is not worth a shared build-dependency
/// crate.
const FNV_OFFSET_BASIS: u64 = 0xcbf2_9ce4_8422_2325;

/// FNV-1a 64-bit prime. See [`FNV_OFFSET_BASIS`] for why this is duplicated.
const FNV_PRIME: u64 = 0x0000_0100_0000_01b3;

/// Unit separator byte, mixed in after every hashed component (a path, a
/// file's contents), matching the discipline in `talkbank-model`'s
/// fingerprint code: two different splits of the same byte stream cannot
/// collide. ASCII Unit Separator (`0x1F`) never appears in a source path.
const UNIT_SEPARATOR: u8 = 0x1F;

/// Fold one byte into an FNV-1a accumulator.
const fn fnv1a_byte(mut hash: u64, byte: u8) -> u64 {
    hash ^= byte as u64;
    hash = hash.wrapping_mul(FNV_PRIME);
    hash
}

/// Fold every byte of a slice into an FNV-1a accumulator.
fn fnv1a_bytes(mut hash: u64, bytes: &[u8]) -> u64 {
    for byte in bytes {
        hash = fnv1a_byte(hash, *byte);
    }
    hash
}

/// Generate a build-time fingerprint of this grammar crate's own sources:
/// `grammar.js` (the hand-authored source of truth) and the generated
/// `src/parser.c` (tree-sitter's compiled-down parse tables).
///
/// # Why these two files, not the whole crate
///
/// Unlike `talkbank-model`'s behaviour fingerprint (which hashes its entire
/// `src/` tree because validation predicates are entangled throughout that
/// crate), this grammar crate's PARSE behaviour is fully determined by
/// `grammar.js` and its generated `src/parser.c`: everything else here
/// (bindings, queries, docs) does not change what parses. Hashing exactly
/// these two files, in a fixed order, keeps the fingerprint free of
/// incidental churn (a binding comment edit) while still catching every
/// change that can alter what a `.cha` file parses to, including a
/// `grammar.js` edit whose `tree-sitter generate` output happens to produce
/// byte-identical `parser.c` for unrelated reasons (rare, but the `grammar.js`
/// hash still changes in that case) and a `tree-sitter generate` run against
/// an unchanged `grammar.js` that nonetheless emits different `parser.c`
/// bytes (a tree-sitter CLI version bump; the `parser.c` hash catches this
/// even though `grammar.js` did not change).
///
/// # Why this exists
///
/// `talkbank-cache`'s `RulesVersion` keys the validation-result cache to the
/// active rule set, but deliberately depends only on `talkbank-model`, not on
/// this grammar crate (inverting that dependency is banned; see
/// `talkbank-cache/src/rules_version.rs`). A grammar change alters what
/// parses, which alters what validates, so a cached verdict from before a
/// grammar change must not be served after one. `GRAMMAR_FINGERPRINT` is the
/// value a caller who already depends on both this crate (via
/// `talkbank-parser`) and `talkbank-cache` folds into
/// `RulesVersion::current_with_config`'s mandatory `parser_fingerprint`
/// parameter.
///
/// Relative paths only, never absolute: an absolute path would make the
/// fingerprint depend on where the repository happens to be checked out,
/// which would invalidate every cache on every machine whose checkout path
/// differs, for no behavioural reason.
fn generate_grammar_fingerprint() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let crate_root = Path::new(&manifest_dir);

    // Fixed, already-sorted order: exactly the two files that determine what
    // this grammar parses. Unlike `talkbank-model`'s whole-tree walk, there is
    // no directory recursion here, so no sort-after-collect step is needed.
    const HASHED_RELATIVE_PATHS: [&str; 2] = ["grammar.js", "src/parser.c"];

    let mut hash = FNV_OFFSET_BASIS;
    for relative_path in HASHED_RELATIVE_PATHS {
        println!("cargo:rerun-if-changed={relative_path}");

        hash = fnv1a_bytes(hash, relative_path.as_bytes());
        hash = fnv1a_byte(hash, UNIT_SEPARATOR);

        let full_path = crate_root.join(relative_path);
        let content = fs::read(&full_path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", full_path.display()));
        hash = fnv1a_bytes(hash, &content);
        hash = fnv1a_byte(hash, UNIT_SEPARATOR);
    }

    let fingerprint = format!("{hash:016x}");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = PathBuf::from(&out_dir).join("grammar_fingerprint.rs");
    let mut file = fs::File::create(&dest_path).unwrap();
    writeln!(
        file,
        "/// Build-time fingerprint of this grammar crate's own sources \
         (`grammar.js` and the generated `src/parser.c`). Generated by \
         build.rs; see its `generate_grammar_fingerprint` doc comment.\n\
         pub const GRAMMAR_FINGERPRINT: &str = {fingerprint:?};",
    )
    .unwrap();
}

/// Compile generated grammar C sources and expose optional query cfg flags.
fn main() {
    generate_grammar_fingerprint();

    // Compile the generated parser (and optional scanner) into the Rust crate.
    let src_dir = std::path::Path::new("src");

    let mut c_config = cc::Build::new();
    c_config.std("c11").include(src_dir);

    #[cfg(target_env = "msvc")]
    c_config.flag("-utf-8");

    // WASM builds need libc shims provided by tree-sitter-language.
    if std::env::var("TARGET").unwrap() == "wasm32-unknown-unknown" {
        let Ok(wasm_headers) = std::env::var("DEP_TREE_SITTER_LANGUAGE_WASM_HEADERS") else {
            panic!("Environment variable DEP_TREE_SITTER_LANGUAGE_WASM_HEADERS must be set by the language crate");
        };
        let Ok(wasm_src) =
            std::env::var("DEP_TREE_SITTER_LANGUAGE_WASM_SRC").map(std::path::PathBuf::from)
        else {
            panic!("Environment variable DEP_TREE_SITTER_LANGUAGE_WASM_SRC must be set by the language crate");
        };

        c_config.include(&wasm_headers);
        c_config.files([
            wasm_src.join("stdio.c"),
            wasm_src.join("stdlib.c"),
            wasm_src.join("string.c"),
        ]);
    }

    let parser_path = src_dir.join("parser.c");
    c_config.file(&parser_path);
    // No `cargo:rerun-if-changed` print here: `generate_grammar_fingerprint`
    // already emits it for the same relative path ("src/parser.c").

    let scanner_path = src_dir.join("scanner.c");
    if scanner_path.exists() {
        c_config.file(&scanner_path);
        println!("cargo:rerun-if-changed={}", scanner_path.to_str().unwrap());
    }

    c_config.compile("tree-sitter-talkbank");

    // Gate query constants behind cfg flags only when query files are present.
    println!("cargo:rustc-check-cfg=cfg(with_highlights_query)");
    if !"queries/highlights.scm".is_empty()
        && std::path::Path::new("queries/highlights.scm").exists()
    {
        println!("cargo:rustc-cfg=with_highlights_query");
    }
    println!("cargo:rustc-check-cfg=cfg(with_injections_query)");
    if !"queries/injections.scm".is_empty()
        && std::path::Path::new("queries/injections.scm").exists()
    {
        println!("cargo:rustc-cfg=with_injections_query");
    }
    println!("cargo:rustc-check-cfg=cfg(with_locals_query)");
    if !"queries/locals.scm".is_empty() && std::path::Path::new("queries/locals.scm").exists() {
        println!("cargo:rustc-cfg=with_locals_query");
    }
    println!("cargo:rustc-check-cfg=cfg(with_tags_query)");
    if !"queries/tags.scm".is_empty() && std::path::Path::new("queries/tags.scm").exists() {
        println!("cargo:rustc-cfg=with_tags_query");
    }
}
