#![cfg_attr(docsrs, feature(doc_cfg, doc_auto_cfg))]
#![deny(missing_docs)]
//! This crate provides TalkBank CHAT language support for the [tree-sitter] parsing library.
//!
//! Typically, you will use the [`LANGUAGE`] constant to add this language to a
//! tree-sitter [`Parser`], and then use the parser to parse some code:
//!
//! # Start here
//!
//! - [`LANGUAGE`] registers the grammar with a tree-sitter parser
//! - [`NODE_TYPES`] exposes the generated node-type schema as a static string
//! - optional query constants such as [`HIGHLIGHTS_QUERY`] and [`TAGS_QUERY`]
//!   are available when the corresponding generated binding cfgs are enabled
//! - [`GRAMMAR_FINGERPRINT`] is a build-time fingerprint of this crate's own
//!   sources, for downstream cache-versioning callers
//!
//! ```
//! let code = "@UTF8\n@Begin\n@End\n";
//! let mut parser = tree_sitter::Parser::new();
//! let language = tree_sitter_talkbank::LANGUAGE;
//! parser
//!     .set_language(&language.into())
//!     .expect("Error loading TalkBank CHAT parser");
//! let tree = parser.parse(code, None).unwrap();
//! assert!(!tree.root_node().has_error());
//! ```
//!
//! [`Parser`]: https://docs.rs/tree-sitter/0.26.6/tree_sitter/struct.Parser.html
//! [tree-sitter]: https://tree-sitter.github.io/

use tree_sitter_language::LanguageFn;

// Edition 2024 requires the `unsafe` on the block itself: declaring a foreign
// symbol is the unsafe act, because nothing checks that this signature matches
// what the generated C actually exports.
unsafe extern "C" {
    /// FFI symbol generated by tree-sitter for this grammar.
    fn tree_sitter_talkbank() -> *const ();
}

/// The tree-sitter [`LanguageFn`] for this grammar.
pub const LANGUAGE: LanguageFn = unsafe { LanguageFn::from_raw(tree_sitter_talkbank) };

/// The content of the [`node-types.json`] file for this grammar.
///
/// [`node-types.json`]: https://tree-sitter.github.io/tree-sitter/using-parsers/6-static-node-types
pub const NODE_TYPES: &str = include_str!("../../src/node-types.json");

// Generated by build.rs: `pub const GRAMMAR_FINGERPRINT: &str`, a hash of
// this crate's own `grammar.js` and generated `src/parser.c` (path + content
// of each, in that fixed order). See `generate_grammar_fingerprint` in
// `bindings/rust/build.rs` for why exactly these two files, and
// `talkbank_cache::RulesVersion::current_with_rule_selection` (in the `talkbank-cache`
// crate) for the cache-versioning composition this feeds, via
// `talkbank_parser::GRAMMAR_FINGERPRINT`.
include!(concat!(env!("OUT_DIR"), "/grammar_fingerprint.rs"));

#[cfg(with_highlights_query)]
/// The syntax highlighting query for this grammar.
pub const HIGHLIGHTS_QUERY: &str = include_str!("../../queries/highlights.scm");

#[cfg(with_injections_query)]
/// The language injection query for this grammar.
pub const INJECTIONS_QUERY: &str = include_str!("../../queries/injections.scm");

#[cfg(with_locals_query)]
/// The local variable query for this grammar.
pub const LOCALS_QUERY: &str = include_str!("../../queries/locals.scm");

#[cfg(with_tags_query)]
/// The symbol tagging query for this grammar.
pub const TAGS_QUERY: &str = include_str!("../../queries/tags.scm");

#[cfg(test)]
mod tests {
    // Test code relaxes the panic family, the same way `talkbank-parser-re2c`
    // does at its own test module. A smoke test that cannot panic cannot fail,
    // and this one exists precisely to fail loudly if the generated language
    // will not register.
    //
    // The relaxation is scoped to this module rather than the crate, and it is
    // written down because `grammar` only came under the workspace lint table
    // on 2026-08-26; before that it declared no `[lints]` stanza and was
    // silently exempt from every workspace lint, which is what hid this site.
    #![allow(clippy::panic, clippy::unwrap_used, clippy::expect_used)]

    /// Smoke test: ensure the generated language can be registered with a parser.
    #[test]
    fn test_can_load_grammar() {
        let mut parser = tree_sitter::Parser::new();
        parser
            .set_language(&super::LANGUAGE.into())
            .expect("Error loading TalkBank CHAT parser");
    }
}
