#!/usr/bin/env python3
"""Fail when a document's `Last modified` header is older than the document.

# Why this exists

The convention is stated in AGENTS.md: a touched doc updates its `Last
modified` from real `date` output. Nothing enforced it, and on 2026-08-11 a
measurement found the header LYING on 56 of 86 book pages, some claiming March
against files committed in August. Two pages carried no date at all.

A date header that is wrong is worse than none: a reader uses it to decide
whether to trust the page, which is exactly what AGENTS.md's staleness rule
tells them to do.

# Why a ratchet rather than a sweep

AGENTS.md also says NOT to bulk-stamp dates on docs you have not verified,
because that manufactures confidence in pages nobody read. So this does not
demand the backlog be fixed at once. The baseline records the pages already
stale when the check was introduced; the check fails on any page NOT in it, and
equally fails when a baseline page is fixed but left listed, so the list can
only shrink.

Fixing a baseline entry means READING the page and correcting it, then removing
its line. That is the only way out, deliberately.

# What "stale" means here

The stated date is older than the date of the last commit that touched the
file. That is mechanical and needs no judgement: if the bytes changed after the
date the page claims, the claim is false.

A publication date is not a content-review date. Prefer Git-owned publication
metadata: a book chapter's `{{git-dates:page}}` header is rendered by mdBook;
other documents can link to their own Git history. Both follow actual commits,
including content-preserving squashes, without claiming another content review.
Handwritten dates retain the existing prospective edit and history checks.

`--prospective --snapshot index` checks staged changes against HEAD for an
ordinary commit. With the default worktree snapshot, `--prospective` checks
changes since the configured upstream for a future squash, falling back to
HEAD without an upstream (including detached CI). That worktree mode includes
new and unstaged documents; deleted documents do not participate in either mode.
The gate and commit hook use these distinct scopes: a content-only gate receipt cannot
prove a history-dependent date check after a later commit. CI still checks the
actual committed dates. No dates are automatically rewritten.
"""

from __future__ import annotations

import argparse
import datetime
import re
import subprocess
import sys
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from urllib.parse import quote

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE = REPO_ROOT / "scripts" / "doc-dates-baseline.txt"

DATE_HEADER = re.compile(
    r"^\*\*(?:Last (?:modified|updated)|This page last changed):\*\*[^\S\n]*(.+)$",
    re.MULTILINE,
)
MANUAL_DATE = re.compile(r"^(\d{4}-\d{2}-\d{2})(?:\s|$)")
HISTORY_URL = "https://github.com/TalkBank/chatter/commits/main/"

# A book page can carry `{{git-dates:page}}` instead of a hand-written date:
# `scripts/mdbook_git_dates.py` substitutes the page's last commit date at build
# time. Such a page has no claim to check, because its date is derived from the
# same history this script would compare it with, so it is honest by construction.
GIT_DERIVED_DATE = "{{git-dates:page}}"


@dataclass(frozen=True)
class HandwrittenDate:
    date: datetime.date


@dataclass(frozen=True)
class GitPublicationDate:
    """Metadata bound to its own rendered chapter or Git history."""


@dataclass(frozen=True)
class InvalidDateHeader:
    reason: str


DateClaim = HandwrittenDate | GitPublicationDate | InvalidDateHeader


def date_claim(path: str, text: str) -> DateClaim:
    """Admit the metadata header, never a placeholder example in the body."""
    header = DATE_HEADER.search(text)
    if header is None:
        return InvalidDateHeader("no `Last modified` header")
    value = header.group(1).strip()
    if value == GIT_DERIVED_DATE:
        if path.startswith("book/src/") and path != "book/src/SUMMARY.md":
            return GitPublicationDate()
        return InvalidDateHeader("a page date placeholder requires a rendered book chapter")
    history = HISTORY_URL + quote(path)
    if value == f'<a href="{history}">Git history</a>':
        return GitPublicationDate()
    if value == f"[Git history]({history})" and path != "book/src/SUMMARY.md":
        return GitPublicationDate()
    manual = MANUAL_DATE.match(value)
    if manual is None:
        return InvalidDateHeader("expected a date or Git publication metadata bound to this document")
    try:
        return HandwrittenDate(datetime.date.fromisoformat(manual.group(1)))
    except ValueError:
        return InvalidDateHeader("invalid calendar date in `Last modified` header")


# What this check does NOT govern, and why:
#
# - `docs/errors/` is GENERATED by `just spec-gen`; its currency is its
#   generator's business.
# - `spec/errors/` and `spec/constructs/` are spec DATA, not prose. They carry
#   their own metadata and are gated by the spec runners (`just spec-status`),
#   which check something far stronger than a date.
# - Anything under a `generated/` directory, for the same reason as the first.
# - `CHANGELOG.md`, a release log whose dates are its content.
# - `spec/observations/` is GENERATED by `just spec-gen` (the R3 snapshot and
#   its README); its currency gate is the artifact byte-compare, and a
#   hand-dated header on a generated file would be stale by construction.
# - GitHub's issue and pull-request TEMPLATES. Their content is not read as a
#   document; it is COPIED into every issue and pull request somebody opens, so
#   a `Last modified` header there would appear in the body of each one,
#   pre-dated and meaningless to the person filling it in. They were in the
#   backlog only because the collector took every tracked `*.md`, and the only
#   way to clear them was to put a date where a date does harm.
EXCLUDED_PREFIXES = (
    # Generated by audit_check_parity; byte currency is checked by its owner.
    "docs/audits/check-parity-audit.md",
    "book/src/architecture/errors-and-validation/check-parity-audit.md",
    "docs/errors/",
    "spec/errors/",
    "spec/constructs/",
    "spec/observations/",
    ".github/ISSUE_TEMPLATE/",
)
EXCLUDED_PARTS = ("/generated/",)
EXCLUDED_NAMES = ("CHANGELOG.md", "PULL_REQUEST_TEMPLATE.md")


class Snapshot(Enum):
    """The bytes being checked: a proposed gate tree or the actual Git index."""

    WORKTREE = "worktree"
    INDEX = "index"

    def read(self, path: str) -> str:
        if self is Snapshot.INDEX:
            return subprocess.run(
                ["git", "show", f":{path}"], cwd=REPO_ROOT,
                capture_output=True, text=True, check=True,
            ).stdout
        return (REPO_ROOT / path).read_text(encoding="utf-8")


def tracked_markdown(snapshot: Snapshot) -> list[str]:
    options = ["--cached"]
    if snapshot is Snapshot.WORKTREE:
        options.extend(["--others", "--exclude-standard"])
    out = subprocess.run(
        ["git", "ls-files", *options, "-z", "*.md"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split("\0")
    return [
        path
        for path in sorted(set(out))
        if path and (snapshot is Snapshot.INDEX or (REPO_ROOT / path).is_file())
        and not path.startswith(EXCLUDED_PREFIXES)
        and not any(part in path for part in EXCLUDED_PARTS)
        and Path(path).name not in EXCLUDED_NAMES
    ]


def refuse_if_shallow() -> None:
    """A shallow clone makes this check silently vacuous, so refuse to run in one.

    `git log -1 -- <path>` returns NOTHING for a file no commit in the shallow
    range touched, which this treats as "never committed" and therefore not
    stale. On a depth-1 CI checkout that is almost every file, so the gate would
    report clean while checking nothing. Fail loudly instead.
    """
    shallow = subprocess.run(
        ["git", "rev-parse", "--is-shallow-repository"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    if shallow == "true":
        sys.exit(
            "check_doc_dates: this is a SHALLOW clone, so per-file commit dates are "
            "not knowable and this check would pass without checking anything. "
            "Check out with full history (`fetch-depth: 0`)."
        )


def last_commit_date(path: str) -> str | None:
    """The date of the last commit touching `path`, or None if never committed."""
    out = subprocess.run(
        ["git", "log", "-1", "--format=%cs", "--", path],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    return out or None


def prospective_paths(snapshot: Snapshot) -> set[str]:
    """Changes the selected snapshot's commit operation would re-date.

    The index represents an ordinary commit, relative to HEAD. Only the
    worktree's squash preview uses the published boundary and unstaged pages.
    Committed history is still checked separately. No second checkout is made.
    """
    base = "HEAD"
    if snapshot is Snapshot.WORKTREE:
        upstream = subprocess.run(
            ["git", "rev-parse", "--verify", "@{upstream}"],
            cwd=REPO_ROOT, capture_output=True, text=True, check=False,
        )
        if upstream.returncode == 0:
            base = upstream.stdout.strip()
    options = ["--cached"] if snapshot is Snapshot.INDEX else []
    changed = subprocess.run(
        ["git", "diff", *options, "--name-only", "-z", base, "--", "*.md"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    ).stdout
    paths = set(changed.split("\0"))
    if snapshot is Snapshot.INDEX:
        return paths
    untracked = subprocess.run(
        ["git", "ls-files", "--others", "--exclude-standard", "-z", "*.md"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    ).stdout
    return paths | set(untracked.split("\0"))


def stale_reason(path: str, snapshot: Snapshot, prospective_date: str | None = None) -> str | None:
    """Why `path` is stale, or None when its header is honest."""
    text = snapshot.read(path)
    match date_claim(path, text):
        case GitPublicationDate():
            return None
        case InvalidDateHeader(reason):
            return reason
        case HandwrittenDate(date):
            stated = date.isoformat()
    committed = last_commit_date(path)
    if prospective_date is not None:
        committed = max(committed, prospective_date) if committed else prospective_date
    if committed is None:
        return None
    if stated < committed:
        boundary = "prospective commit" if prospective_date else "last commit"
        return f"header says {stated}, {boundary} {committed}"
    return None


def read_baseline(snapshot: Snapshot) -> set[str]:
    path = str(BASELINE.relative_to(REPO_ROOT))
    if snapshot is Snapshot.INDEX:
        present = subprocess.run(
            ["git", "ls-files", "--cached", "--", path], cwd=REPO_ROOT,
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    else:
        present = BASELINE.is_file()
    if not present:
        return set()
    return {
        line.strip()
        for line in snapshot.read(path).splitlines()
        if line.strip() and not line.startswith("#")
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--prospective", action="store_true",
        help="also check pending commit/squash changes against today's local date",
    )
    parser.add_argument(
        "--snapshot", choices=[snapshot.value for snapshot in Snapshot],
        default=Snapshot.WORKTREE.value,
        help="check worktree bytes for a gate or index bytes for a commit",
    )
    parser.add_argument(
        "--write-baseline",
        action="store_true",
        help="record the current stale set as the baseline (for introducing the check)",
    )
    args = parser.parse_args()

    refuse_if_shallow()

    snapshot = Snapshot(args.snapshot)
    pending = prospective_paths(snapshot) if args.prospective else set()
    today = datetime.datetime.now().astimezone().date().isoformat()
    stale = {
        path: reason for path in tracked_markdown(snapshot)
        if (reason := stale_reason(path, snapshot, today if path in pending else None))
    }

    if args.write_baseline:
        BASELINE.write_text(
            "# Docs whose `Last modified` header was already stale when\n"
            "# scripts/check_doc_dates.py was introduced (2026-08-11).\n"
            "#\n"
            "# This list may only SHRINK. To remove a line: READ the page, correct\n"
            "# what is wrong, update its header from real `date` output, and delete\n"
            "# the line. Do not bulk-stamp dates on pages nobody has read; that\n"
            "# manufactures confidence, which is the failure this check exists for.\n"
            + "".join(f"{path}\n" for path in sorted(stale)),
            encoding="utf-8",
        )
        print(f"baseline written: {len(stale)} doc(s)")
        return 0

    baseline = read_baseline(snapshot)
    new = {path: reason for path, reason in stale.items() if path not in baseline or path in pending}
    fixed = sorted(baseline - set(stale))

    for path, reason in sorted(new.items()):
        print(f"STALE: {path}: {reason}", file=sys.stderr)
    if new:
        print(
            f"\n{len(new)} doc(s) have a `Last modified` header older than the file.\n"
            "Update the header from real `date '+%Y-%m-%d %H:%M %Z'` output in the\n"
            "same commit as the edit.",
            file=sys.stderr,
        )

    for path in fixed:
        print(f"FIXED (remove from the baseline): {path}", file=sys.stderr)
    if fixed:
        print(
            f"\n{len(fixed)} baseline doc(s) are no longer stale. Delete their lines\n"
            f"from {BASELINE.relative_to(REPO_ROOT)} so the list keeps shrinking.",
            file=sys.stderr,
        )

    if new or fixed:
        return 1

    print(f"doc dates: ok ({len(baseline)} known-stale doc(s) remaining)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
