#!/usr/bin/env python3
"""Fail when a document's `Last modified` header is older than the document.

# Why this exists

The convention is stated in CLAUDE.md: a touched doc updates its `Last
modified` from real `date` output. Nothing enforced it, and on 2026-08-11 a
measurement found the header LYING on 56 of 86 book pages, some claiming March
against files committed in August. Two pages carried no date at all.

A date header that is wrong is worse than none: a reader uses it to decide
whether to trust the page, which is exactly what CLAUDE.md's staleness rule
tells them to do.

# Why a ratchet rather than a sweep

CLAUDE.md also says NOT to bulk-stamp dates on docs you have not verified,
because that manufactures confidence in pages nobody read. So this does not
demand the backlog be fixed at once. The baseline records the pages already
stale when the check was introduced; the check fails on any page NOT in it, and
equally fails when a baseline page is fixed but left listed, so the list can
only shrink.

Fixing a baseline entry means READING the page and correcting it, then removing
its line. That is the only way out, deliberately.

# What "stale" means here

The stated date is older than the date of the last commit that touched the
file. That is mechanical and needs no judgement: if the bytes changed after the
date the page claims, the claim is false.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BASELINE = REPO_ROOT / "scripts" / "doc-dates-baseline.txt"

DATE_HEADER = re.compile(r"\*\*Last (?:modified|updated):\*\*\s*(\d{4}-\d{2}-\d{2})")

# What this check does NOT govern, and why:
#
# - `docs/errors/` is GENERATED by `gen_error_docs`; its currency is its
#   generator's business.
# - `spec/errors/` and `spec/constructs/` are spec DATA, not prose. They carry
#   their own metadata and are gated by the spec runners (`just spec-status`),
#   which check something far stronger than a date.
# - Anything under a `generated/` directory, for the same reason as the first.
# - `CHANGELOG.md`, a release log whose dates are its content.
EXCLUDED_PREFIXES = ("docs/errors/", "spec/errors/", "spec/constructs/")
EXCLUDED_PARTS = ("/generated/",)
EXCLUDED_NAMES = ("CHANGELOG.md",)


def tracked_markdown() -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "*.md"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split()
    return [
        path
        for path in out
        if not path.startswith(EXCLUDED_PREFIXES)
        and not any(part in path for part in EXCLUDED_PARTS)
        and Path(path).name not in EXCLUDED_NAMES
    ]


def refuse_if_shallow() -> None:
    """A shallow clone makes this check silently vacuous, so refuse to run in one.

    `git log -1 -- <path>` returns NOTHING for a file no commit in the shallow
    range touched, which this treats as "never committed" and therefore not
    stale. On a depth-1 CI checkout that is almost every file, so the gate would
    report clean while checking nothing. Fail loudly instead.
    """
    shallow = subprocess.run(
        ["git", "rev-parse", "--is-shallow-repository"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    if shallow == "true":
        sys.exit(
            "check_doc_dates: this is a SHALLOW clone, so per-file commit dates are "
            "not knowable and this check would pass without checking anything. "
            "Check out with full history (`fetch-depth: 0`)."
        )


def last_commit_date(path: str) -> str | None:
    """The date of the last commit touching `path`, or None if never committed."""
    out = subprocess.run(
        ["git", "log", "-1", "--format=%cs", "--", path],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()
    return out or None


def stale_reason(path: str) -> str | None:
    """Why `path` is stale, or None when its header is honest."""
    text = (REPO_ROOT / path).read_text(encoding="utf-8")
    match = DATE_HEADER.search(text)
    if match is None:
        return "no `Last modified` header"
    committed = last_commit_date(path)
    if committed is None:
        return None
    stated = match.group(1)
    if stated < committed:
        return f"header says {stated}, last commit {committed}"
    return None


def read_baseline() -> set[str]:
    if not BASELINE.exists():
        return set()
    return {
        line.strip()
        for line in BASELINE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.startswith("#")
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write-baseline",
        action="store_true",
        help="record the current stale set as the baseline (for introducing the check)",
    )
    args = parser.parse_args()

    refuse_if_shallow()

    stale = {path: reason for path in tracked_markdown() if (reason := stale_reason(path))}

    if args.write_baseline:
        BASELINE.write_text(
            "# Docs whose `Last modified` header was already stale when\n"
            "# scripts/check_doc_dates.py was introduced (2026-08-11).\n"
            "#\n"
            "# This list may only SHRINK. To remove a line: READ the page, correct\n"
            "# what is wrong, update its header from real `date` output, and delete\n"
            "# the line. Do not bulk-stamp dates on pages nobody has read; that\n"
            "# manufactures confidence, which is the failure this check exists for.\n"
            + "".join(f"{path}\n" for path in sorted(stale)),
            encoding="utf-8",
        )
        print(f"baseline written: {len(stale)} doc(s)")
        return 0

    baseline = read_baseline()
    new = {path: reason for path, reason in stale.items() if path not in baseline}
    fixed = sorted(baseline - set(stale))

    for path, reason in sorted(new.items()):
        print(f"STALE: {path}: {reason}", file=sys.stderr)
    if new:
        print(
            f"\n{len(new)} doc(s) have a `Last modified` header older than the file.\n"
            "Update the header from real `date '+%Y-%m-%d %H:%M %Z'` output in the\n"
            "same commit as the edit.",
            file=sys.stderr,
        )

    for path in fixed:
        print(f"FIXED (remove from the baseline): {path}", file=sys.stderr)
    if fixed:
        print(
            f"\n{len(fixed)} baseline doc(s) are no longer stale. Delete their lines\n"
            f"from {BASELINE.relative_to(REPO_ROOT)} so the list keeps shrinking.",
            file=sys.stderr,
        )

    if new or fixed:
        return 1

    print(f"doc dates: ok ({len(baseline)} known-stale doc(s) remaining)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
