//! The generated artifacts that need the live PARSER, and therefore cannot
//! live in `spec/tools`.
//!
//! This is the second half of the registry whose first half is
//! [`generators::artifacts::ARTIFACTS`]. The split is not organisational: it is
//! the dependency boundary this crate exists to draw. `spec/tools` reads
//! markdown and writes files and never links the parser or model; anything
//! that has to RUN the parser belongs here.
//!
//! That criterion said "needs the live `ErrorCode` enum" until R1's review,
//! and by then it was false of everything left in the crate: the snapshot
//! needs the PARSER, and the book table needs nothing at all. The true
//! statement was written thirty lines below the false one, which is the
//! correction-appended-under-a-stale-claim shape this workspace forbids.
//!
//! `spec_gen` runs both halves, so a contributor sees one command and one list.

use std::path::Path;

use anyhow::Result;
use generators::artifacts::{Artifact, GeneratedFiles, Ownership};

/// The observation snapshot, which regenerates BEFORE everything else.
///
/// R3 of the spec-system redesign: for every spec example, what the current
/// binary actually emits, by stage, and whether the parsed model serializes
/// back byte-exact. A diff is adjudicated, never silently regenerated.
///
/// Its own slice rather than a row below, because [`all`] yields it FIRST:
/// since R4, the tree-sitter corpus DERIVES its membership from this file, so
/// generating in declaration order would read a stale snapshot on any
/// behaviour change and need a second run to converge. The registry is a DAG
/// and the iteration order is its topological sort.
pub static SNAPSHOT_ARTIFACT: &[Artifact] = &[Artifact {
    what: "example-diagnostics observation snapshot",
    root: "spec/observations",
    ownership: Ownership::WholeDirectory,
    build: crate::observations::build_snapshot,
}];

/// Artifacts that must run AFTER the pure half, and the one that runs the
/// parser.
///
/// The `DiagnosticKind` registry LEFT this list under R1. It read
/// `ErrorCode::iter()` only to join the enum's vocabulary against the specs';
/// with both generated from one registry there is nothing to join, so it is a
/// pure TOML-to-Rust transform and lives in the other half.
///
/// Neither survivor is here for the same reason. `build_snapshot` runs the
/// tree-sitter parser, which is the crate boundary. `build_book_artifact_table`
/// needs no parser and no model: it is here because it iterates [`all`], so it
/// must be downstream of everything it describes. Two reasons, stated, rather
/// than one criterion that covers neither.
pub static RUNTIME_ARTIFACTS: &[Artifact] = &[Artifact {
    what: "the book's artifact table",
    root: "book/src/architecture/generated",
    ownership: Ownership::NamedFiles { retired: &[] },
    build: build_book_artifact_table,
}];

/// The file name of the book's generated artifact table.
const BOOK_TABLE_FILE: &str = "spec-artifacts.md";

/// The book's table of what is generated and where it lands.
///
/// # Why the book's table is itself an artifact
///
/// It was hand-written, and it listed five generators when the tree had
/// eighteen binaries; the four it named as separate commands had by then become
/// one. A table beside the list it describes is the defect this whole registry
/// exists to remove, so the registry generates it and the currency gate keeps
/// it true. The row for this file is in the table, which is correct: a reader
/// should be able to see that the page is derived.
fn build_book_artifact_table(_repo_root: &Path) -> Result<GeneratedFiles> {
    // Built line by line rather than from one continued literal: a trailing
    // backslash keeps the SOURCE indentation, which put nine spaces in front of
    // every header row and rendered the table as an indented code block.
    let mut table = String::new();
    table.push_str(
        "<!-- Generated by `just spec-gen` from the artifact registry. DO NOT EDIT: change the registry. -->\n\n",
    );
    table.push_str("| Artifact | Committed at | Directory ownership |\n");
    table.push_str("|---|---|---|\n");
    for artifact in all() {
        let ownership = match artifact.ownership {
            Ownership::WholeDirectory => "the whole directory, cleared on every run",
            Ownership::NamedFiles { .. } => "only the files it produces",
        };
        table.push_str(&format!(
            "| {} | `{}/` | {} |
",
            artifact.what, artifact.root, ownership
        ));
    }
    let mut files = GeneratedFiles::new();
    files.insert(BOOK_TABLE_FILE.into(), table);
    Ok(files)
}

/// EVERY artifact, both halves of the registry.
///
/// The chain used to be written out at each of three call sites (the binary
/// and the gate's two tests), and only one of them carried the reason for the
/// order, so the other two could drift out of it silently. "Every artifact" is
/// a concept; this is where it lives.
///
/// The order is deliberate: the pure-markdown half first, so a failure there
/// is reported before the half that has to link the model runs.
pub fn all() -> impl Iterator<Item = &'static Artifact> {
    // Topological order, not declaration order: the snapshot first, because
    // the tree-sitter corpus in the generators half reads it as an input.
    SNAPSHOT_ARTIFACT
        .iter()
        .chain(generators::artifacts::ARTIFACTS.iter())
        .chain(RUNTIME_ARTIFACTS.iter())
}
